### ISSUE TITLE
Subtle fixes and improvement in README.md

### ISSUE THREAD

**Issue by Ankesh2004** [Tanay-ErrorCode/lupo-skill#1]
There are a few errors in readme.md which needs to be fixed and improvements can be made.
Kindly assign me this issue under GSSOC'24.

**Comment by Doraemon012** [comment]
@Tanay-ErrorCode I would like to work on this issue. Please assign this to me.

**Comment by Doraemon012** [comment]
@Tanay-ErrorCode I have a doubt.
