### ISSUE TITLE
feat: Smooth scroll animation effetcs.

### ISSUE THREAD

**Issue by yashi-15** [Tanay-ErrorCode/lupo-skill#100]
**Is your feature request related to a problem? Please describe.**
It is a feature request where I would like to make the website look more modern and engaging.

**Describe the solution you'd like**
I want to incorporate smooth and subtle scroll animation effects for the website elements. These elements will seamlessly appear as you scroll through the page.

**Additional context**
Kindly assign this issue to me under GSSOC'24, so that I can start working on it.

**Comment by Doraemon012** [comment]
@yashi-15 You can work on this.
Please add the described effects to **home page only**.

**Comment by Tanay-ErrorCode** [comment]
@yashi-15 Any updates?

**Comment by yashi-15** [comment]
Hi @Tanay-ErrorCode, I will create the PR by tomorrow...
