### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by Hemashree21** [Tanay-ErrorCode/lupo-skill#101]
I want to work on designing the About page so that users can gain a better understanding about the features of the website. Here is one of the templates. I'll make sure the page is responsive as well
@Tanay-ErrorCode can you please assign this to me?

![Screenshot 2024-05-13 180820](https://github.com/Tanay-ErrorCode/lupo-skill/assets/138188163/99cf6a24-02b1-4fe4-92e7-3b55d8942c8d)

**Comment by Doraemon012** [comment]
@Hemashree21 We have the About section in the footer of the website, we do not need a separate page for that.
