### ISSUE TITLE
Add issues template for documentation issues

### ISSUE THREAD

**Issue by suhanipaliwal** [Tanay-ErrorCode/lupo-skill#103]
I would like to add a issues template for documentation issues in this repository. I believe that having a standardised template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review issues.

Could you please assign this issue to me under GSSOC'24.

**Comment by Doraemon012** [comment]
@suhanipaliwal We do not need this. 
If you want to contribute, please look for any other issue in the website. You can also take up any of the open issues if you wish to.
