### ISSUE TITLE
[Feat]: Implement Footer Section for Enhanced Navigation and Information

### ISSUE THREAD

**Issue by Dhevamuthu** [Tanay-ErrorCode/lupo-skill#108]
The current project lacks a footer section, which is essential for providing users with quick access to important links and information. Adding a footer will enhance the overall usability and professionalism of the website. The proposed footer will include clear sections for "Quick Links," "Contact Information," "Social Media," and "About Us," ensuring users can easily navigate to key areas of the site and find relevant information. Additionally, the footer will be designed with a consistent style that matches the website's overall aesthetic and will be responsive to ensure a seamless experience across all devices. This enhancement will improve navigation, accessibility, and the user experience.

**Comment by EmazinUs** [comment]
@Tanay-ErrorCode, I would like to fix this issue. Please assign me this under GSSOC'24.

**Comment by Doraemon012** [comment]
An issue is already open for this.
