### ISSUE TITLE
feat: Adding gap between navbar and the Events heading so that the UI looks more smoother and good.

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Tanay-ErrorCode/lupo-skill#111]
[Screenshot 2024-05-24 182412](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/e651eedc-732e-4c03-ac3b-347cfb7268bf)

**Is your feature request related to a problem? Please describe.**
There is no space between events heading and the navbar and the font of events heading can be changed so that the UI looks better.

**Describe the solution you'd like**
Adding margin to the heading and adding letter spacing and changing the font size and font style of the heading.

**Describe alternatives you've considered**

**Additional context**

**Comment by AnirbanChattopadhyay-2004** [comment]
please assign this issue to me so that I can have  a contribution under gssoc 24.

**Comment by Doraemon012** [comment]
This bug is already fixed.
