### ISSUE TITLE
bug :  'Continue With Google' Button Visible on Home Screen Even When Signed In

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#112]
### **Describe the bug**
When a user is signed in, the **'Continue With Google'** button remains visible on the **home screen**. This button should not be visible if the user is already signed in.

### **To Reproduce**

1. Go to `https://lupo-skill.web.app/`
2. Sign in to the website.
3. Go to the home page.
4. Observe the 'Continue With Google' button.

### **Expected behavior**
The **'Continue With Google'** button should be **hidden** when the user is already signed in.

### **Screenshots**

![Screenshot - Sign in button - visible](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/0dc7bb61-f09f-4e34-b81a-41371376cdf5)

### **Additional context**
No additional context.

**Comment by EmazinUs** [comment]
@Tanay-ErrorCode, I would like to fix this issue. Please assign me this under GSSOC'24.

**Comment by Doraemon012** [comment]
@EmazinUs We assign issues on a first-come, first-served basis. If you would like, you can take up any other open issues or open one yourself if needed.
