### ISSUE TITLE
feat: Redesign Event Card

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#113]
### **Is your feature request related to a problem? Please describe.**
The current event card component needs a redesign to improve visual appeal and functionality.

### **Describe the solution you'd like**
- Redesign the event card component to align with the theme defined in `theme.tsx`.
- Ensure the component is fully responsive to different screen sizes.
- Utilize the [MUI card component](https://mui.com/material-ui/react-card/).
- Use `MUI` and `CSS`
- The new UI must look as close as possible to the Figma design.

### **Additional context**
- Below is a screenshot of the desired event card UI for reference.
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/828b969a-697f-4096-9020-2b0e4bc542b8)

- The exact design can be found in this [figma design](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=14-174&t=ygGyLPPd7qlvcPlU-1).
- This screen recording shows how get exact colors and values from a figma design.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/c1fe8e14-50af-46b6-b473-5dbeecbe3748

**Comment by prachita0504** [comment]
please add level  also

**Comment by Utsavladia** [comment]
Dear @Doraemon012 
I understood the required Deisgn for Event card and before finding this issue also I felt it should be redesigned so I believe I can make it a good one and enhance the user experience.

kindly assign this to me ✨

**Comment by Tejsvapandey1** [comment]
can i work on this please

**Comment by Utsavladia** [comment]
Dear @Doraemon012  
how can i contact you If I have any issue in this.

**Comment by Annu117** [comment]
Can i work on this?

**Comment by Utsavladia** [comment]
I am unable to login using signInWithGooglePopup It gives some error in console like "popup.ts:302 Cross-Origin-Opener-Policy policy would block the window.closed call." it would be greate if I could get the help setting up this.
