### ISSUE TITLE
bug : Not verifying whether it is instagram link or not.

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Tanay-ErrorCode/lupo-skill#115]
**Describe the bug**
In the profile, in the edit section it is not being verified that it is an instagram link and upon putting any other link it is considering it and redirecting to that particular link.
**To Reproduce**

1. Go to lupo website.
2. Click on profile
3. Scroll down to edit
4. Apply any link in the link section for any social media.
5. open it
6. it will redirect to that link without having a check of the typed link.
7. See error

**Expected behavior**
on clicking save if it is not the link it should show an alert for that.
**Screenshots**
Add screenshots to help explain your problem.
[Screenshot 2024-05-25 113453](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/2124791d-6a88-449c-9c90-b624fbe934a4)

**Additional context**
Please assign this issue to me so that I can have a contribution under gssoc24.

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 Please add the functionality that all the three links are verified.

**Comment by AnirbanChattopadhyay-2004** [comment]
Sir can you please assign the level for this issue

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 The level will be assigned after completing the PR.

**Comment by AnirbanChattopadhyay-2004** [comment]
Ok sir

**Comment by AnirbanChattopadhyay-2004** [comment]
Sir actually exams are going on thats why its taking time. I will try to resolve this issue by today

**Comment by AnirbanChattopadhyay-2004** [comment]
At my time of working on this project the social media field was missing so I added it and verified it.

**Comment by AnirbanChattopadhyay-2004** [comment]
I have resolved this issue.Please merge my pr.
