### ISSUE TITLE
bug : Profile image on navbar persists after changing profile picture

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#117]
## **Describe the bug**
The profile image displayed in the navigation bar fails to refresh after a user updates their profile picture. The old image remains visible even after the new image has been uploaded and confirmed.

## **To Reproduce**
1. Log in to the application.
2. Navigate to the profile settings page.
3. Update the profile picture with a new image and save the changes.
4. Return to the main page with the navigation bar.
5. Notice that the old profile image is still displayed.

## **Expected behavior**
The profile image in the navigation bar should immediately reflect the newly uploaded profile picture without the need to refresh or log out.

## **Screenshots**
None

## **Additional context**
None

**Comment by nishant0708** [comment]
Hey please assign me this issue
