### ISSUE TITLE
feat: Redesign the Navbar component

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#118]
### **Is your feature request related to a problem? Please describe.**
Redesign the `navbar` component.

### **Describe the solution you'd like**
Redesign the navbar to ensure it's visually appealing, consistent across pages, and flexible in its layout. The specifications are:
- Utilize `Material-UI (mui)` and `CSS` for styling.
- The Navbar should be Sticky.
- **There should be a single navbar component adaptable to the home screen and the other screens**.
- Use the[ MUI App Bar Component](https://mui.com/material-ui/react-app-bar/).
- The functionality should be same as the existing Navbar.

### **Additional context**

- Screenshots of the desired navbar design:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/740e668f-b614-42e4-b38e-0c8d9f3691bc)
- The exact design can be found in this [figma file](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=174-786&t=upBP1TkxavtzxW1i-1).

- This screen recording shows how get exact colors and values from a figma design.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/c1fe8e14-50af-46b6-b473-5dbeecbe3748

**Comment by Utsavladia** [comment]
Dear @Doraemon012 ,
I understood this issue of redesigning the navbar and believe I can make it the way you asked above and enhance the experience of users.
Kindly assign this to me I would love to conntribute to this project.

**Comment by nishant0708** [comment]
hey i would also like to work on this issue.

**Comment by Doraemon012** [comment]
@Utsavladia Please complete this ASAP.
