### ISSUE TITLE
feat:  Add footer section

### ISSUE THREAD

**Issue by Saimanjari777** [Tanay-ErrorCode/lupo-skill#121]
**Is your feature request related to a problem? Please describe.**
There is no footer present in this website which consists of description about website, copyright details, subscription button, and social media icons.

**Describe the solution you'd like**
I would like to add this section,

**Describe alternatives you've considered**
I would like to add the above details I have mentioned.

**Additional context**
I am working under GSSoC'24
Please assign this issue to me @Tanay-ErrorCode

**Comment by Doraemon012** [comment]
An issue is already open for this. You can take up any other open issues, or open one if needed.
