### ISSUE TITLE
Add an About Page

### ISSUE THREAD

**Issue by Hemashree21** [Tanay-ErrorCode/lupo-skill#129]
I want to work on designing an About Page to highlight the main features of the website so that whenever any user enters the website, they will get to know the purpose and features of it.  I will also make sure that the page is responsive. Here is one of the templated for reference.

![Uploading Screenshot 2024-05-17 162211.png…]()

@Tanay-ErrorCode can you please assign this to me?

**Comment by Tanay-ErrorCode** [comment]
@Hemashree21 We have the About section in the footer of the website, we do not need a separate page for that. I have already closed issue #101 .

**Comment by Tanay-ErrorCode** [comment]
@Hemashree21 You can open any other issue.

**Comment by Hemashree21** [comment]
@Tanay-ErrorCode are you planning to add a footer to the website?

**Comment by Tanay-ErrorCode** [comment]
@Hemashree21 Yes, unfortunately a PR is already open for this #126 .

**Comment by Tanay-ErrorCode** [comment]
@Hemashree21 If you can redesign the Edit profile popup, that will be good. You can raise an issue for it. Here are our [figma designs](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=1-2&t=tQRBOEZD1p18InHd-0), you can take the basic idea of color theme and other UI.
