### ISSUE TITLE
Redesign Edit Profile Popup

### ISSUE THREAD

**Issue by Hemashree21** [Tanay-ErrorCode/lupo-skill#130]
@Tanay-ErrorCode I want to work on redesigning the edit profile page, can you please assign this to me?

**Comment by Doraemon012** [comment]
@Hemashree21 Please describe your approach and the designs.

**Comment by Doraemon012** [comment]
@Hemashree21 Please give detailed **figma designs** with the same fields that currently are in our application.

**Comment by Tanay-ErrorCode** [comment]
@Hemashree21 Any updates?

**Comment by Hemashree21** [comment]
@Tanay-ErrorCode I am not that familiar with Figma so I don't have any designs in mind.

**Comment by Tanay-ErrorCode** [comment]
@Hemashree21 Then how will you redesign the popup? For redesigning something, we must at least have some design in mind.

**Comment by Hemashree21** [comment]
I have sent an image above, I can redesign according to that
