### ISSUE TITLE
event info page

### ISSUE THREAD

**Issue by Annu117** [Tanay-ErrorCode/lupo-skill#132]
**Is your feature request related to a problem? Please describe.**
Can I build this page as created in Figma. 

**Describe the solution you'd like**
Build and make it interactive.

**Additional context**

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by Doraemon012** [comment]
There's no `Event info page` in the figma design.
