### ISSUE TITLE
bug : Not able to create a event

### ISSUE THREAD

**Issue by Yash-Ainapure** [Tanay-ErrorCode/lupo-skill#133]
**Describe the bug**
I am not able to create a new event in create events page, I am also logged in in using google
and the response after filling all the input boxes it is telling to fill it(below is the video of the bug).

**To Reproduce**

1. Go to 'Create event '
2. fill all the inputs
3. click on create to see the error

**Expected behavior**
It should tell what the problem is such as user not logged in / this field is empty ,etc
 add a better validation of create event card

**Screenshots**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/136250383/abd38495-5910-4805-9547-3dde841a48b8

**Comment by Doraemon012** [comment]
@Yash-Ainapure the tags should be separated by hitting enter.
