### ISSUE TITLE
feat: Adding an animation to the navbar elements while hovering .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Tanay-ErrorCode/lupo-skill#134]
**Is your feature request related to a problem? Please describe.**
I want to add the sliding line with animation when user hovers on the navbar elements i think this will increase the UX of the website .

**Describe the solution you'd like**
Adding an animation

![Screenshot 2024-05-28 150001](https://github.com/Tanay-ErrorCode/lupo-skill/assets/118350936/1aa943eb-ecd9-433b-9dcd-f1bf2d1be13e)

**Comment by yash28goyal** [comment]
I would like to Contribute to this project please assign this issue to me.
