### ISSUE TITLE
bug : [Button name is login but shows sign  up make it both login and sign up]

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Tanay-ErrorCode/lupo-skill#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/125277258/d38c3f35-abcc-403e-8383-9362949838cf)

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@RamakrushnaBiswal Please go through [this ](https://www.npmjs.com/package/react-google-button). You just have to add a prop to the existing button.

**Comment by RamakrushnaBiswal** [comment]
@Tanay-ErrorCode yh sure
