### ISSUE TITLE
bug : IN Mobile screen Navbar is not Closing automatically

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#139]
**Describe the bug**
Nav bar should get closed automatically which is not happening in mobile
**To Reproduce**

1. In mobile click on navbar icon 
2. Click on  any otion
3. navbar stays open it should get close

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/649093b0-b751-40cc-be38-62304096569a)

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 A PR was already merged for this, so it is working fine.
