### ISSUE TITLE
Want to add LICENSE.md 

### ISSUE THREAD

**Issue by Sowham-3098** [Tanay-ErrorCode/lupo-skill#140]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Sowham-3098 Elaborate please.

**Comment by Doraemon012** [comment]
We do not need this. You can check out any other open issues, or open one by yourself if needed.
