### ISSUE TITLE
feat: Add animation to the testimonials section.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#142]
## **Is your feature request related to a problem? Please describe.**
The testimonials section lacks animation, making it less engaging compared to other animated sections on the website. This inconsistency affects the overall user experience and visual appeal.

## **Describe the solution you'd like**
Add animations to the testimonials section to match the animations of the rest of the homepage.

## **Describe alternatives you've considered**
None

## **Additional context**
None

**Comment by nishant0708** [comment]
Can I Work On This ISSUE?
