### ISSUE TITLE
Redesign the EVENTS page.

### ISSUE THREAD

**Issue by yashi-15** [Tanay-ErrorCode/lupo-skill#144]
**Is your feature request related to a problem? Please describe.**
The event page and its cards lack a good design.

**Describe the solution you'd like**
I aim to redesign the page while maintaining the website's overall theme. The cards will be styled using flex design, with a refreshed look and feel. Additionally, I plan to incorporate a smooth scrolling animation effect with framer-motion on the EVENTS page.

**Additional context**
I want to work on this issue under GSSOC'24.

**Comment by Doraemon012** [comment]
@Yashi-15 We already have a design for the events page and event cards [here](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=1-2&t=gUEUA9LzDIAhXKi6-1). If you have any better designs, please share them here.

**Comment by yashi-15** [comment]
> @yashi-15 We already have a design for the events page and event cards [here](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=1-2&t=gUEUA9LzDIAhXKi6-1). If you have any better designs, please share them here.


I would implement this design on the website. You can assign this issue to me.
