### ISSUE TITLE
bug : There is no arrow slider visible for the happy user card section

### ISSUE THREAD

**Issue by Maheshwari-Love** [Tanay-ErrorCode/lupo-skill#145]
**Describe the bug**

There should be a arrow showing slide to left or right

**To Reproduce**

1. Go to  [website](https://lupo-skill.web.app/)
2. on click left or right the card should move accordingly
3. But there is now  arrow given for that.

**Expected behavior**
There should be the left and right arrow given on "Happy user" section so that user experience can be made better.
Some thing like this 
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/142833275/9c37cd59-421f-45ce-8b0c-996dc5649042)

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/142833275/3e71f8d3-efaa-48aa-a1a0-a2e1362e8f70)

**Comment by Tanay-ErrorCode** [comment]
@Maheshwari-Love We are using [react-bootstrap carousel](https://react-bootstrap.netlify.app/docs/components/carousel/).

**Comment by Maheshwari-Love** [comment]
@Tanay-ErrorCode level label?

**Comment by Tanay-ErrorCode** [comment]
@Maheshwari-Love Raise the PR first.
