### ISSUE TITLE
Add: GPL License for Open Source Compliance

### ISSUE THREAD

**Issue by mdazfar2** [Tanay-ErrorCode/lupo-skill#148]
## Is your feature request related to a problem? Please describe.
I propose adding a GPL (GNU General Public License) to the Lupo-skill repository to ensure it adheres to open source licensing standards.

## Describe the solution you'd like
- 📝 Lack of License: Currently, the SoundScape repository does not have a license specified.
- 📜 Open Source Compliance: Adding a GPL license will make the project legally compliant with open source requirements and clearly define usage terms.

## Describe alternatives you've considered
- 🏷️ Add GPL License: Implement the GNU General Public License (GPL) to protect both contributors and users, ensuring the project remains free and open source.
- 📂 License File: Create a LICENSE file in the repository root with the full text of the GPL.

@Tanay-ErrorCode   Looking forward to your feedback and the opportunity to help implement this important addition.

**Comment by Tanay-ErrorCode** [comment]
We do no need this.
