### ISSUE TITLE
AUTO COMMENTING: When someone raise new Issues

### ISSUE THREAD

**Issue by mdazfar2** [Tanay-ErrorCode/lupo-skill#150]
## Description:

I propose adding a workflow file to the repository that automatically commits changes when a new issue is opened. This automation will streamline the development process and ensure timely updates.

## Issue Details:

- 📝 Manual Commits: Currently, commits must be made manually when an issue is opened, which can be time-consuming and prone to delays.
- ⚙️ Automation: Implementing an automated workflow will enhance efficiency and consistency.

## Screenshots-

![image](https://github.com/avinashkranjan/logsuite/assets/100375390/c5945b63-bea3-4799-913d-d8cc818654fe)

## Benefits:

- ⏱️ Time-Saving: Automates repetitive tasks, saving valuable time for contributors and maintainers.
- 🔄 Consistency: Ensures that all issues are promptly followed by the necessary commits, maintaining a consistent update process.
- 📈 Improved Workflow: Enhances the overall workflow by reducing manual steps and potential human errors.

@Tanay-ErrorCode   please assign this issues to me

**Comment by Tanay-ErrorCode** [comment]
@mdazfar2 We already have a similar github actions bot. It works both for issues and PRs. We have disabled it for now. Can you change it so that it does not make any comments whenever the project admin (repo owner in our case) and the mentors (collaborators in our repo) create an issue or raise a PR ?

**Comment by mdazfar2** [comment]
@Tanay-ErrorCode what you are exact talking about could you please elaborate it

**Comment by Tanay-ErrorCode** [comment]
> @Tanay-ErrorCode what you are exact talking about could you please elaborate it

Please elaborate your idea first?

**Comment by mdazfar2** [comment]
@Tanay-ErrorCode When someone raises a `new issue`, the `GitHub-action` will automatically comment, and this is possible with the workflow file called `yaml`.

<br/>

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/100375390/751571fb-6d46-4f03-b0c4-9f1e01b3895c)

**Comment by Tanay-ErrorCode** [comment]
> We already have a similar github actions bot. It works both for issues and PRs. We have disabled it for now. Can you change it so that it does not make any comments whenever the project admin (repo owner in our case) and the mentors (collaborators in our repo) create an issue or raise a PR ?

This means that:

- We already have a GitHub Action Workflow for commenting on issues and PRs.
- It is currently disabled.
- The GitHub Actions bot should not comment on issues or PRs created by the project admin or mentors.

Hope you will understand.

**Comment by Tanay-ErrorCode** [comment]
If you can do this, then please proceed.
