### ISSUE TITLE
feat:  Add footer 

### ISSUE THREAD

**Issue by aasthakourav20** [Tanay-ErrorCode/lupo-skill#152]
**Is your feature request related to a problem? Please describe.**
The project don't have any footer

**Describe the solution you'd like**
I would like to add a responsive Footer to the project

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by Doraemon012** [comment]
We do not need this. We already have a footer. You can check out any other open issues, or open one by yourself if needed.
