### ISSUE TITLE
bug : Users Can Edit Name in Profile Edit Section

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#153]
### **Describe the bug**
Users are able to edit their name in the profile edit section, which should not be allowed.

### **To Reproduce**

1. Go to 'Profile'
2. Click on 'Edit Profile'
3. See that the 'Name' field is editable

### **Expected behavior**
The 'Name' field should be non-editable to prevent users from changing their name.

### **Screenshots**
None.

### **Additional context**
This issue allows users to change their display name, which could lead to inconsistencies in user identification across the platform.

**Comment by nishant0708** [comment]
hey can i work on it ?

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Work on this.
