### ISSUE TITLE
feat: Dynamic Banner Color on Signup

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#156]
## **Is your feature request related to a problem? Please describe.**
Currently, when users sign up on the site, a default image is set as their banner. The banner should initially be a simple color (random) instead of an image.

## **Describe the solution you'd like**
For signups, the user's banner should set to a random color within the banner continer. No image should be set initially. The banner image should only be uploaded and displayed when the user changes the default banner color to an image of their choice.

## **Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/1f40a7ce-77b6-40bf-bd41-35976ee5d6f9)

## **Describe alternatives you've considered**
None

## **Additional context**
Use these preset colors
```js
const randomColors = [
  "#FFEBEE",
  "#E3F2FD",
  "#E8F5E9",
  "#FFFDE7",
  "#F3E5F5",
  "#FFF3E0",
  "#E0F7FA",
  "#FFF0E1",
  "#F8F4FF",
  "#E0F2F1"
];
```

**Comment by nishant0708** [comment]
can i work on this issue?

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012 please assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
