### ISSUE TITLE
feat: Search bar in events page would be very much helpful

### ISSUE THREAD

**Issue by mukilan2815** [Tanay-ErrorCode/lupo-skill#157]
**Is your feature request related to a problem? Please describe.**
If there is a search bar in events page it will be easier for user.
**Describe the solution you'd like**
I will add a search bar
**Describe alternatives you've considered**
none
**Additional context**
none

**Screenshot**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/71129858/6ec8c9f3-7866-4607-8986-4e514511e1be)

**Comment by Doraemon012** [comment]
@mukilan2815 Please describe your approach.

**Comment by mukilan2815** [comment]
I will add a contact form for support and then a search bar in events page so that if user needs to search by event name he can search the event by event name in search bar

**Comment by Doraemon012** [comment]
@mukilan2815 No need to add a contact form. For the search bar, use [MUI](https://mui.com/material-ui/getting-started/) and css, style it according to the website's theme.

**Comment by mukilan2815** [comment]
Yeah sure please assign me
