### ISSUE TITLE
bug : Add Grid Layout in events 

### ISSUE THREAD

**Issue by dhruv8433** [Tanay-ErrorCode/lupo-skill#162]
@Tanay-ErrorCode 

**Describe the bug**
- we can add grid layout and instead of displaying single card we can displaty 4 cards in row

**To Reproduce**

1. Go to `/event` page

**Expected behavior**
- we need grid layout 

**Screenshots**
Add screenshots to help explain your problem.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/114583978/93718e02-0e37-4cf4-95df-7651a59e9ac2)

**Additional context**

**Comment by ayushkamboj18** [comment]
hey, I can do it, assign me

**Comment by Shweta-281** [comment]
👋 Hello! @dhruv8433 
I'd be happy to help with this issue. Could you please assign it to me?

**Comment by Doraemon012** [comment]
@dhruv8433 @ayushkamboj18 @Shweta-281 This bug is already being addressed in another open issue. Please feel free to take up any other open issues; you can also open one if needed.
