### ISSUE TITLE
feat: Dynamic Addition of Social Media URL Fields in Edit Profile Modal

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#163]
## **Is your feature request related to a problem? Please describe.**
The current **Edit Profile** modal is too large because it shows many fields for different social media URLs (like Facebook, Instagram, Twitter) all at once. This makes it hard to use.

## **Describe the solution you'd like**
Start with only one input field for a social media URL and a **plus (+) button**. When the user clicks the plus button, a new input field should appear, allowing them to add another social media URL. Users should be able to add **3 URLs at max**.

## **Screenshots**
Current edit profile popup on mobile phone

<img src="https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/81643209-43a9-427f-bd6a-abd123f475dd" width="360" height="640"/>

## **Describe alternatives you've considered**
None

## **Additional context**
This change will make the modal cleaner and easier to use, providing a better user experience by allowing users to add social media URLs as needed rather than displaying all possible fields at once.

**Comment by nishant0708** [comment]
Hey can i work on this issue
