### ISSUE TITLE
feat: Add animation to all the modals

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#164]
## **Is your feature request related to a problem? Please describe.**
Currently there is no popup animation in any of the Popup Modals (EditProfile, LogIn/SignUp and CreateEvent). Add a slow fade animation.

## **Describe the solution you'd like**
Add a slow fade animation to display the modals.

## **Describe alternatives you've considered**
None

## **Additional context**
None

**Comment by nishant0708** [comment]
please Assign me this issue
