### ISSUE TITLE
bug : SignUp/LogIn Popup and Toast Displayed When User is Logged Out.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#165]
## **Describe the Bug**
When the user is logged out and clicks on **Dashboard** in the navbar, it opens both the **Login/Signup**modal and a toast saying "You are not signed in." The toast should not be displayed; only the sign-in modal should appear.

## **To Reproduce**

1. Log out from the website.
2. Click on **Dashboard** in the navbar.
3. Observe the appearance of the toast and the modal.

## **Expected Behavior**
Only the sign-in modal should open, without any additional popups or toasts.

## **Screenshots**
![Screenshot of the issue](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/94be17e8-4df3-4be2-b8e3-2d29d0090d75)

## **Additional Context**
None

**Comment by nishant0708** [comment]
please assign me this issue
