### ISSUE TITLE
feat: Their should be option to delete created event by user.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#167]
**Is your feature request related to a problem? Please describe.**
Currently, users do not have the option to delete events they have created. This can lead to clutter and confusion if events are canceled or no longer relevant.

**Describe the solution you'd like**
Implement a feature that allows users to delete events they have created. This option should be easily accessible from the event management interface and should confirm the deletion action to prevent accidental deletions.

**Describe alternatives you've considered**
- Providing an option to archive events instead of deleting them, so they are no longer active but still retrievable.
- Allowing users to mark events as canceled, which would remove them from active listings but retain the information.

**Additional context**
This feature would help users manage their events more effectively, keeping their event list organized and relevant. Consider implementing confirmation prompts and ensuring that deleting an event does not affect other users or linked data inadvertently.

**Comment by nishant0708** [comment]
Hey can i work on this??

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
