### ISSUE TITLE
feat: Option to remove registration of registered event.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#168]
## **Is your feature request related to a problem? Please describe.**
Users who have registered for events may need to cancel their registration due to changes in their schedules or other commitments. Currently, there is no option to remove registration from an event, which can cause inconvenience and potential issues with event attendance records.

## **Describe the solution you'd like**
Implement a feature that allows users to remove registration from events they have registered for. This option should be accessible from the event details or and should provide confirmation to prevent accidental remove registration.

## **Describe alternatives you've considered**
None

## **Additional context**
This feature would improve user experience by providing flexibility and control over their event registrations. It would also help event organizers maintain accurate attendance records and plan accordingly.

**Comment by nishant0708** [comment]
Can i work on this issue
