### ISSUE TITLE
bug : [re-design the footer]

### ISSUE THREAD

**Issue by Varsani2520** [Tanay-ErrorCode/lupo-skill#172]
**Describe the bug**
i want to re design the footer ,footer is important part of website,where user can click and go to that page 
**To Reproduce**
design footer
add important point
apply link
use social media field 

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.
before:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/137641079/e7a089c9-68d6-403f-87fc-7fc2b08a26c2)
i will do it like this and also additional icons :
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/137641079/708590d2-b03b-44dd-a950-60c2266e28dd)

**Additional context**

**Comment by Varsani2520** [comment]
@Tanay-ErrorCode ,assign this issue

**Comment by Tanay-ErrorCode** [comment]
@Varsani2520 This is our footer, if your have any better designs, please share them here.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/31a11b96-6e9e-4710-930d-f332d93f47c7)

**Comment by Varsani2520** [comment]
choose :
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/137641079/11220fa2-cf73-4862-a446-c0fa9b0d8183)
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/137641079/541a79ba-1b46-43cb-a860-206a4f888dc2)

**Comment by Tanay-ErrorCode** [comment]
@Varsani2520 Give figma designs instead of screenshots.

**Comment by Tanay-ErrorCode** [comment]
@Varsani2520 Can you improfve this?

**Comment by Tanay-ErrorCode** [comment]
@Varsani2520 Can you improve this?


![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/31a11b96-6e9e-4710-930d-f332d93f47c7)

**Comment by Varsani2520** [comment]
yes , i can do it @Tanay-ErrorCode

**Comment by Doraemon012** [comment]
@Varsani2520 Please explain what improvements will you make ?

**Comment by Doraemon012** [comment]
This is the [link](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=59-33&t=ZZonWVAxX4gqibnm-1) to our figma design.

**Comment by Varsani2520** [comment]
@Doraemon012 

i can update your footer and add social media links
also i can add subscription button where user submit then email and got notification from us
also additional link like quick links  of Home,about ,contact ..

also update look of the footer and make it responsive too...

**Comment by Varsani2520** [comment]
@Doraemon012 

please response
as a mentor, it's your responsibility to give response

i am redesign your footer and i also give you choice too
please select from that choice

**Comment by Doraemon012** [comment]
@Varsani2520 Thanks a lot for making me aware of my responsibilities. We do not need to redesign the footer.
