### ISSUE TITLE
bug : [apply grid in event section]

### ISSUE THREAD

**Issue by Varsani2520** [Tanay-ErrorCode/lupo-skill#173]
**Describe the bug**
i want to add grid ,if we add grid then website look like cool also enjoy the user for more visit the website
**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.
before:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/137641079/9d07d815-3677-4d6c-b9b4-87258bdb6528)
i will do it like this:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/137641079/90b03066-84c8-4718-bb8e-81e5b8ab05a8)

**Additional context**

**Comment by Doraemon012** [comment]
@Varsani2520 This bug is already being addressed in another issue.
