### ISSUE TITLE
feat: Hover effect to the Happy user section

### ISSUE THREAD

**Issue by Damini2004** [Tanay-ErrorCode/lupo-skill#175]
**Is your feature request related to a problem? Please describe.**
This will help to grab more user engagement.
**Describe the solution you'd like**
This will helps the user experience for better in UI designing.
**Describe alternatives you've considered**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/ded23f10-614f-43df-aa75-272eb54c6730)
**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Damini2004 Go ahead.

**Comment by Damini2004** [comment]
@Tanay-ErrorCode  Kindly assign label too

**Comment by Doraemon012** [comment]
@Damini2004 The level will be assigned once you raise a PR for the issue.
