### ISSUE TITLE
feat: add `scroll bar`

### ISSUE THREAD

**Issue by Ketanop321** [Tanay-ErrorCode/lupo-skill#177]
**Is your feature request related to a problem? Please describe.**
making a good appealing scroll bar

**Describe the solution you'd like**
::webkit: scroll bar

**Describe alternatives you've considered**
I will use html ,css and js to build this 
**Additional cont
![Screenshot 2024-06-01 212648](https://github.com/Tanay-ErrorCode/lupo-skill/assets/146806880/39b06972-1d27-4040-86c1-69f10b6dc2d6)
ext**

**Comment by Tanay-ErrorCode** [comment]
@Ketanop321 Please make scrollbar similar to this, specially check the hover effect. This is firefox default scrollbar.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/564f4f60-cd20-4e06-8534-52656486a69c

**Comment by Gamerking177** [comment]
pls assign me @Tanay-ErrorCode
