### ISSUE TITLE
bug : Navbar Overlapping Event Details Card

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#182]
### **Describe the bug**
Navbar overlapping the card in event details page.

### **To Reproduce**

1. Go to events page
2. Register for an event
3. Go to dashboard
4. Click on the event card you registered.
5. Observe the overlapping

### **Expected behavior**
The navbar should not overlap the card in the event details page. The card content should be clearly visible without any obstruction from the navbar.

### **Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/b01fbccd-0044-4e18-840a-756b23834ae3)

### **Additional context**
none

**Comment by nishant0708** [comment]
can i work on this issue

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead.
