### ISSUE TITLE
bug : Footer Overlapping Pagination Buttons

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#183]
### **Describe the bug**
Footer overlapping the pagination buttons

### **To Reproduce**

1. Go to events page
2. Click on pagination buttons
3. Due to footer overlap, pagination does not happen

### **Expected behavior**
Pagination buttons should be fully visible and clickable without any obstruction from the footer. Pagination should work smoothly.

### **Screenshots**

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/caa9f816-f3f3-4262-aa52-8e8a0f0f826d)

### **Additional context**

When fixing this issue, also watch the other pages to ensure the footer does not overlap any other elements.

**Comment by nishant0708** [comment]
please assign me this issue

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead.
