### ISSUE TITLE
bug : White Space Appears When Scrolling Right on Mobile View (Homepage)

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#184]
**Describe the bug**
White space is visible when scrolled right on mobile view (homepage of website).

**To Reproduce**

1. Go to the homepage of the website on a mobile device.
2. Scroll to the right.
3. Observe the white space appearing on the right side.

**Expected behavior**
The website should be fully responsive on mobile devices with no white space visible when scrolling to the right. The content should fit within the screen width.

**Screenshots**
<img src="https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/8768267f-bb5a-4035-980f-56acaf2c18c6" width=360 height=640/>

**Additional context**
None

**Comment by nishant0708** [comment]
please assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
