### ISSUE TITLE
Feature: add codeql workflow for `typescript`

### ISSUE THREAD

**Issue by harmeetsingh11** [Tanay-ErrorCode/lupo-skill#19]
### Describe your improvement idea or feature request

The repository contains code in `typescript`, it does not have workflow for code scanning. 

### How would you like to see it implemented?

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I am a GSSoC'2024 contributor

**Comment by Doraemon012** [comment]
@harmeetsingh11 I am closing this for now, we can reopen this later.

We have planned to gradually the complexity of the project. Currently the project is in its initial stage where we are adding new basic features. We will move on to testing and other advanced features once the basic project is ready. The basic part is estimated to complete within a few days.
