### ISSUE TITLE
bug : Current navbar looks outdated

### ISSUE THREAD

**Issue by kashnx** [Tanay-ErrorCode/lupo-skill#190]
I can make the navbar look better and design it according to modern websites.

**Comment by Doraemon012** [comment]
@kashnx Please share your designs.

**Comment by Tanay-ErrorCode** [comment]
@kashnx Any updates?

**Comment by kashnx** [comment]
will update you today

**Comment by kashnx** [comment]
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/148524648/573434e2-534a-4e03-b862-12fd6b1e3456)
kind of this. will change the colors according to the site

**Comment by Tanay-ErrorCode** [comment]
>  kind of this. will change the colors according to the site and add logo in the starting

@kashnx This is good. Please give the design that aligns with theme of our website.

**Comment by kashnx** [comment]
> > kind of this. will change the colors according to the site and add logo in the starting
> 
> @kashnx This is good. Please give the design that aligns with theme of our website.

Will start working on it today.
