### ISSUE TITLE
feat: Make stylish Scrollbar.

### ISSUE THREAD

**Issue by zalabhavy** [Tanay-ErrorCode/lupo-skill#191]
**Is your feature request related to a problem? Please describe.**
I want to add style to scrollbar.

**Describe the solution you'd like**
I will make stylish scrollbar.

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@zalabhavy Please make scrollbar similar to this, specially check the hover effect. This is firefox default scrollbar.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/564f4f60-cd20-4e06-8534-52656486a69c

**Comment by zalabhavy** [comment]
@Tanay-ErrorCode Done !
