### ISSUE TITLE
Pages not rendering from top

### ISSUE THREAD

**Issue by paulkrishanu4** [Tanay-ErrorCode/lupo-skill#193]
Pages are not rendering from top

https://github.com/Tanay-ErrorCode/lupo-skill/assets/169196836/6b0e6112-4beb-4607-bd82-e8ade452ce67

pages should be rendered from top for better UI experience like this

https://github.com/Tanay-ErrorCode/lupo-skill/assets/169196836/f0f33f81-822c-4c8e-8c99-fd64e7d709ee

ASSIGN ME TO FIX THIS ISSUE

**Comment by Doraemon012** [comment]
@paulkrishanu4 Go ahead.

**Comment by Tanay-ErrorCode** [comment]
@paulkrishanu4 Any updates?

**Comment by paulkrishanu4** [comment]
working on it within tomorrow I will submit the pr
