### ISSUE TITLE
bug: Text does not disappear on sign-in

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#194]
**Describe the bug**
When the user signs in, the button disappears (as intended), but the text and above it do not disappear.

**To Reproduce**
1. Go to the sign-in.
2. Observe that the button disappears.
3. Notice that the text and above the button do not disappear. But button does.

**Expected behavior**
The text above the button should also disappear when the user signs in.

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/98ebbfca-f9bb-4c75-97cd-1dc170d121aa)

**Additional context**
The text need to be hidden along with the button upon user sign-in.

**Comment by nishant0708** [comment]
Can i work on this issue

**Comment by matinshaikh31** [comment]
can i work on this Issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
