### ISSUE TITLE
feat: Convert Create Event Modal to Create Event Page

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#198]
### **Is your feature request related to a problem? Please describe.**
Make create event page.

### **Describe the solution you'd like**
Convert the create event modal into a separate page while maintaining all existing functionalities.
This is the current create event modal:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/dd0ef5be-e695-4a6a-9c84-e2401a768823)

### **Additional context**
The page should have all the existing functionality of the create event modal.

**Comment by Tomkndn** [comment]
Converting a modal to a page with same functionality right?
Kindly assign this task to me.

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn Go ahead.

**Comment by Tomkndn** [comment]
Working on it just review my screenshot then I'll raise PR for it.

**Comment by Tomkndn** [comment]
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/105445488/2d73edae-d6ce-4d5b-98fb-f494ff54a071)
Any Modification?

**Comment by Doraemon012** [comment]
@Tomkndn Ok.
