### ISSUE TITLE
feat: I want to update the footer. I want to contribute under GSSOC'24. 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Tanay-ErrorCode/lupo-skill#199]
**Is your feature request related to a problem? Please describe.**
I want to design the footer in a better way.

**Describe the solution you'd like**
I want to design the footer in a better way.

**Describe alternatives you've considered**
N/A

**Additional context**

Here is an SS of my sample work
![Screenshot_20240609-002033_GitHub.jpg](https://github.com/Tanay-ErrorCode/lupo-skill/assets/123104247/9450904a-b9a3-4400-a057-5daa8f66be4b)

**Comment by Doraemon012** [comment]
@ParnaRoyChowdhury777 If you have a better design then please share.

**Comment by Tanay-ErrorCode** [comment]
@ParnaRoyChowdhury777 Any updates?

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 Any updates?

![Screenshot_20240613-205208_Chrome.jpg](https://github.com/Tanay-ErrorCode/lupo-skill/assets/123104247/9f7231ec-cb46-45f1-900b-f6cfad9f6b6e)


I can replicate something like this and if you want me to make some design in particular, then I ll be happy to do it.
Thank you.

**Comment by Tanay-ErrorCode** [comment]
@ParnaRoyChowdhury777 Please give design of footer of less height and matching to our website's theme. And we have less fields to display.
