### ISSUE TITLE
Sign In with google popup fails

### ISSUE THREAD

**Issue by Ankesh2004** [Tanay-ErrorCode/lupo-skill#2]
When we try to signin with google popup, it fails showing :

`Cross-Origin-Opener-Policy policy would block the window.closed`

I can fix this , so kindly assign me this issue under GSSOC'24.

**Comment by anuni03** [comment]
I find this error can fix it in backend. Please assign this issue under GSSOC 2024

**Comment by masterboy376** [comment]
@Ankesh2004, this not a issue with the code IMO. To solve it you should just add google auth provider to your firebase project.

**Comment by Ankesh2004** [comment]
This bug has  been fixed already, @Tanay-ErrorCode close this issue

**Comment by Ankesh2004** [comment]
This bug has been fixed already, @Tanay-ErrorCode closing this issue
