### ISSUE TITLE
feat: Creating a custom 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Tanay-ErrorCode/lupo-skill#201]
**Is your feature request related to a problem? Please describe.**
feat: Creating a custom 404 not found page for your website,the default 404 not found page is not good looking
so we can add some gif or images to style it

**Describe the solution you'd like**

**Describe alternatives you've considered**
here now it looks like
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/125277258/b548a5f3-ec7b-4051-82c3-c98a0372d259)

**Additional context**

**Comment by Doraemon012** [comment]
@RamakrushnaBiswal Go ahead.

**Comment by RamakrushnaBiswal** [comment]
hi @Doraemon012 this page is already exist
