### ISSUE TITLE
feat: Add the glowing cursor 

### ISSUE THREAD

**Issue by namandude** [Tanay-ErrorCode/lupo-skill#202]
I would like to add the  glowing cursor effect so when where ever user take their cursor it appears glowing and adding beautiful look in the website.

Like this : 
![Screenshot 2024-06-08 025235](https://github.com/Tanay-ErrorCode/lupo-skill/assets/118013565/86b4048b-d9e3-4d2b-8200-9308e875fd1d)
Please assign this to me under Gssosc.
Thank YOu

**Comment by Doraemon012** [comment]
@namandude We do not need this.
