### ISSUE TITLE
feat: Add a Review Us/Contact us Page

### ISSUE THREAD

**Issue by komal-agarwal5** [Tanay-ErrorCode/lupo-skill#205]
**Is your feature request related to a problem? Please describe.**
I wish to add a page through which people can send their reviews suggestions or any other information (ui form connected with formspree)

**Describe the solution you'd like**
This will help to get a better idea of the interests of the users

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@komal-agarwal5 Closing as not planned. Please checkout other issues or open new one.
