### ISSUE TITLE
feat: Implement UI for In-App Notifications 

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#206]
#### **Is your feature request related to a problem? Please describe.**
To add an in-app notification feature, we need to design and implement the user interface.

#### **Describe the solution you'd like**
The solution requires creating the UI components necessary for in-app notifications.

#### **Describe alternatives you've considered**
None.

#### **Additional context**
- Implement the UI as follows:
    - Add a notifications icon button in the navbar.
        - Use this icon: `import NotificationsIcon from '@mui/icons-material/Notifications';`
    - Add a badge on the icon to indicate unread notifications.
        - Use the [MUI badge component](https://mui.com/material-ui/react-badge/).
    - A notifications panel should open when the user clicks the notifications button.
        - Refer to the video example for the notifications panel: 
        
        https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/3fbe6cfa-852e-49d1-8295-babe46f506a8
        
- Ensure the UI integrates with the existing design of the project.
- Use [MUI](https://mui.com/material-ui/all-components/).
- Refrain from using hardcoded values; the theme (colors, font sizes, border radii, etc.) is available in `App.css` and `theme.tsx`.

**Comment by nishant0708** [comment]
Can I work on this?

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead.
