### ISSUE TITLE
bug : Hover Issue ON carousel Card item

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#208]
**Describe the bug**
When I hover over corner card items it is not hovering properly

**To Reproduce**

1. Go to 'Happy User Section'
2. hover on any corner card name
3. See error

**Expected behavior**
It should work smoothly

**Screenshots**

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/5f452505-55b0-4249-9795-d087be7ca637

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
