### ISSUE TITLE
bug : Changes in Navbar

### ISSUE THREAD

**Issue by BHS-Harish** [Tanay-ErrorCode/lupo-skill#21]
**Describe the bug**
Only logged in users can able to create event and access dashboard.So,
Lets hide the dashboard and create event menu when the user was not logged in

**To Reproduce**
1. Go to 'https://lupo-skill.web.app/'
2. See the options "Dashboard" and "Create event" in nav bar

**Expected behavior**
The dashboard and create event option only visible to logged in users.

**Comment by BHS-Harish** [comment]
Hello @Doraemon012 

Please assign the issue to me

Thanks in advance

**Comment by Doraemon012** [comment]
@BHS-Harish It's better if we not remove the options, because then the navbar will contain only two options.
Instead, if the user tries to access dashboard or goes to create event tab, we can show them a popup for SignIn/SignUp along with the existing toast.
