### ISSUE TITLE
feat: Update Social Media Links Display Logic on Profile

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#211]
### **Is your feature request related to a problem? Please describe.**
The method for storing social media links in the database has changed. Because of this, we need to update how these links are displayed on the user's profile.

### **Describe the solution you'd like**
Update the display logic to match the new way social media links are stored. This should include automatically adding the correct icon for each social media link when it is shown on the profile.

### **Describe alternatives you've considered**
None.

### **Screenshots**
The new structure for a user in database.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/88ffb788-d4da-450a-9099-5a9079224d6e)

### **Additional context**
Currently, there is only functionality to display the Facebook, twitter and Instagram URLs, the application now allows variety of social media URLs. 
You can see the all types of URLs in `./src/utils/InputLink.tsx`

**Comment by nishant0708** [comment]
Please assign it to me
