### ISSUE TITLE
feat: Greeting on Issue Closure

### ISSUE THREAD

**Issue by thevijayshankersharma** [Tanay-ErrorCode/lupo-skill#216]
**Is your feature request related to a problem? Please describe.**
Issue closure lacks a personal touch, leading to a less engaging experience for contributors and stakeholders.

**Describe the solution you'd like**
Upon issue closure, automatically post a greeting message, thanking contributors for their efforts and acknowledging their contribution to the resolution.

**Describe alternatives you've considered**
Manually adding a closing comment on each issue, which is time-consuming and prone to oversight.

**Additional context**
Adding a greeting message upon issue closure would foster a sense of appreciation and recognition among project contributors, enhancing collaboration and morale within the community.

**Comment by Tanay-ErrorCode** [comment]
@thevijayshankersharma  Thanks for opening the issue, but we want to upgrade our project not the github repository. You can take up any of the open issues, or open one by yourself if needed.
