### ISSUE TITLE
 feat: Improve the SEO Implementation

### ISSUE THREAD

**Issue by codercake** [Tanay-ErrorCode/lupo-skill#217]
**Is your feature request related to a problem? Please describe.**
The current implementation lacks adequate search engine optimization (SEO) measures. This affects the visibility and discoverability of the site on search engines, leading to lower traffic and reduced user engagement.

**Describe the solution you'd like**

1. Meta Tags: Add and optimize meta tags (title, description, keywords) for each page.
2. Headings and Structure: Ensure proper use of headings (H1, H2, H3) to enhance content structure.
3. Internal Linking: Create a robust internal linking strategy to improve navigation and reduce bounce rates.
4. XML Sitemap: Generate and submit an XML sitemap to search engines.

**Additional context**
We can significantly improve our site's search engine ranking, attract more visitors, and enhance the overall user experience.

**Comment by Tanay-ErrorCode** [comment]
@codercake Already done in #92. Thanks for opening the issue. You can take up any of the open issues, or open one by yourself if needed.
