### ISSUE TITLE
feat: Redesign Create Event page

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#218]
**Is your feature request related to a problem? Please describe.**
The current **create event page** component needs a redesign to improve visual appeal and functionality.

**Describe the solution you'd like**
- Redesign the **Create Event** component to align with the theme defined in `theme.tsx`.
- Ensure the component is fully responsive to different screen sizes.
- Use `MUI` and `CSS`
- The new UI must look as close as possible to the [Figma design](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=5-22&t=zLzKjSI1Ybs6DV2N-4).

**Describe alternatives you've considered**
None.

**Additional context**

- Below is a screenshot of the desired event card UI for reference.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/ad4c9c42-f9c4-442d-8904-9427bb27fd53)

- The exact design can be found in this [figma design](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=5-22&t=zLzKjSI1Ybs6DV2N-4).
- This screen recording shows how get exact colors and values from a figma design.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/13f8d08d-4851-4137-ac88-f5d850de2249

**Comment by nishant0708** [comment]
hey i would like to work on it

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead,
