### ISSUE TITLE
Events Page UI frontend

### ISSUE THREAD

**Issue by Rohitha-pudu** [Tanay-ErrorCode/lupo-skill#22]
### Events page needs improvement 
The event cards need to be redesigned for better ui
I will work on this issue .Please assign this to me
#Gssoc24

**Comment by Doraemon012** [comment]
@Rohitha-pudu Please proceed with the below given design of Event Card component.
Use React Bootstrap and CSS.

![Frame 271](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/8e2dcd03-5877-4784-9fbc-a614bf8d9eed)

You can take reference from this figma design for exact colors and values.
[Figma](https://www.figma.com/file/ce7ZISlm3vCEGIADOZt0Ma/LUPO-SKILL?type=design&node-id=0%3A1&mode=design&t=4OZ414vJtGAwoVvH-1)

**Comment by Doraemon012** [comment]
We do not have Tailwind in the tech stack of our project. You need to use `React Bootstrap` and `CSS`.

These are the documentation and refrences :
[React Bootstrap Documentation](https://react-bootstrap.netlify.app/)
[CSS | mdn webdocs](https://developer.mozilla.org/en-US/docs/Web/CSS)

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Are you still working on this? Please share your progress (screenshots or screen recoding).

**Comment by Rohitha-pudu** [comment]
actually i don't know firebase authentication,the set up is not ready,but i have written code for it

**Comment by heysagnik** [comment]
> actually i don't know firebase authentication,the set up is not ready,but i have written code for it

hey @Rohitha-pudu just go through firebase docs, you will have a better understanding. If you have any doubts you may ping me on Discord `@heysagnik`

Rest you can start by creating a PR, take your time and add code to that PR.

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Go through [the docs](https://firebase.google.com/docs/web/setup). Follow the step 1 and then paste the firebase config in `src/firebaseConf.ts`

**Note: When you will make a PR, do not push your firebaseConfig.**

**Comment by Rohitha-pudu** [comment]
ok @Tanay-ErrorCode

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Any updates?

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu Any updates?

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116823590/96c8463a-e42d-46e8-bf3c-3fbbf7f3fc92)
on it

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu Any updates?

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116823590/7007c950-747d-4ca9-a878-3a823b2d8025)

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Any updates?

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu Any updates?

I have done all the requested changes ,but due to some issues regarding updates ,my code has been messed up and deleted.
sorry for the late and sorry for bothering ,please assign to someone else.
Thank you for your patience ,for the support and giving me time in knowing firebase and guiding
