### ISSUE TITLE
feat: documentaion : add logo uses techstack

### ISSUE THREAD

**Issue by Debayan-Ghosh2005** [Tanay-ErrorCode/lupo-skill#221]
**Is your feature request related to a problem? Please describe.**
there is no written which tehstack uses in the project

**Describe the solution you'd like**
i will add it in the readme file

**Describe alternatives you've considered**

**Additional context**

**Comment by Debayan-Ghosh2005** [comment]
can you assign it to me

**Comment by Tanay-ErrorCode** [comment]
@Debayan-Ghosh2005 

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/2d4b3039-8ee6-44e3-98ad-3864bd37edc7)

**Comment by Debayan-Ghosh2005** [comment]
![Screenshot 2024-06-14 213345](https://github.com/Tanay-ErrorCode/lupo-skill/assets/149896687/e96c282e-f4f4-4ea9-9f2b-90d693028361)
i will make this type of logo readme file if u assign it to me

**Comment by Tanay-ErrorCode** [comment]
@Debayan-Ghosh2005 We do not need this.
