### ISSUE TITLE
feat: UI can be enhanced

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Tanay-ErrorCode/lupo-skill#222]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
The UI can be enhanced.

**Describe the solution you'd like**
Padding can be added in the heading so that the UI looks appealing.
*Describe alternatives you've considered**
The dark mode features is not working, it can also be rectified.
**Additional context**
[Screenshot 2024-06-17 111919](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/176cf1c5-4985-429c-bc7c-f91b9e51cf22)

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 For this page, issue #113 Is already there.
