### ISSUE TITLE
bug : Not reloading when clicking on the title.

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Tanay-ErrorCode/lupo-skill#223]
**Describe the bug**
The page should reload when clicked on the title but here its not reloading.
**To Reproduce**
Additional link can be added so that the page reloads when clicked on the [link.]([url](url))

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.
|
[Screenshot 2024-06-17 111657](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/2b1831f0-80fb-4e48-b5af-9f278dafc0a9)

**Additional context**

**Comment by AnirbanChattopadhyay-2004** [comment]
Please assign this issue to me as I only wants to contribute in your project.

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 Go ahead.

**Comment by Tanay-ErrorCode** [comment]
@AnirbanChattopadhyay-2004 Any updates?

**Comment by AnirbanChattopadhyay-2004** [comment]
Will do it surely by tomorrow

**Comment by Tanay-ErrorCode** [comment]
Closed as inactive.
