### ISSUE TITLE
feat: Adding hover effect on "Star on GitHub" and "Contribute Now" button

### ISSUE THREAD

**Issue by Monika5S** [Tanay-ErrorCode/lupo-skill#224]
**Is your feature request related to a problem? Please describe.**
"Star on GitHub" and "Contribute Now" button on the home page do not have hover effects which is different from other buttons in the UI. 

**Describe the solution you'd like**
Adding style to the create hover effect to these buttons similar to other buttons on the page which will enhance user experience.

**Describe alternatives you've considered**
Changing background color and adding shadow on hover over the button.

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/92215187/13963070-dbad-4d12-9cbe-14d39ba78b46)

**Comment by Monika5S** [comment]
I can work on implementing this functionality. Kindly approve and assign me this issue.

**Comment by Doraemon012** [comment]
@Monika5S You can now start working on this.

1. Do **NOT** change the background color of the homepage.
2. Make the hover effect of the buttons like that of testimonial card hover.
