### ISSUE TITLE
bug : Search bar is not updating .

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Tanay-ErrorCode/lupo-skill#225]
**Describe the bug**
A clear and concise description of what the bug is .
The search bar is not responding. It is not filtering the events.
**To Reproduce**

1. Go to 'lupo skill' .
2. Click on 'events' .
3. Scroll down to 'search bar' .
4. Type any data to the search bar .
5. data will not filtered .   

**Expected behavior**
It would be good if the data gets filtered as soon as the title is entered .
The data should not filtered .
**Screenshots**
Add screenshots to help explain your problem.
[Screenshot 2024-06-18 104058](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/cc9b1a43-c8e0-4901-acf0-abfcc80fb674)
**Addition
al context**

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 This is intentional, we want the search happen only if we click the button. Closing as not planned.
