### ISSUE TITLE
bug : Dark mode is not working .

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Tanay-ErrorCode/lupo-skill#226]
**Describe the bug**
Real dark mode effect is not updating .
**To Reproduce**
Click on the dark mode button and see the effect . It is not updating the coloring effect .
1. Go to 'lupo skill'
2. Click on 'dark mode '
3. Scroll down to 'any place'
4. See error ( The color will not effect ) .

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.
[Screenshot 2024-06-18 110246](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124513264/7ea18079-0781-41b0-b01e-93553979f874)

**Additional context**

**Comment by Doraemon012** [comment]
@AnirbanChattopadhyay-2004 Let all the pages be redesigned. Then we will open dark mode issues. Closing as not planned.
