### ISSUE TITLE
feat: add Background Animation 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Tanay-ErrorCode/lupo-skill#227]
**Is your feature request related to a problem? Please describe.**
yes 

**Describe the solution you'd like**
I will add an amazing particle animation in the website header page so that it will looks cool 

https://github.com/Tanay-ErrorCode/lupo-skill/assets/118350936/9e198deb-e295-4b8a-8808-c1b29ffcba0c

**Comment by Doraemon012** [comment]
@Ayushmaanagarwal1211 We do not needs this for now. Closing as not planned.
