### ISSUE TITLE
feat: Enhancing the create event page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Tanay-ErrorCode/lupo-skill#228]
**Is your feature request related to a problem? Please describe.**
yes 
**Describe the solution you'd like**
I will enhance the design of the create event page and it is overlapping the the navbar so i will also fix that .

![Screenshot 2024-06-18 130954](https://github.com/Tanay-ErrorCode/lupo-skill/assets/118350936/6aa448f0-a459-4ddc-80c1-a8887491436f)

**Comment by Doraemon012** [comment]
@Ayushmaanagarwal1211 #218 is already open for this. Closing as duplicate. Please take any of the other open issues, or raise a new issue.
