### ISSUE TITLE
feat: Enhancing buttons

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Tanay-ErrorCode/lupo-skill#229]
**Is your feature request related to a problem? Please describe.**
Yes 

**Describe the solution you'd like**
I will replace current button with  an amazing animated button with cool hovering effect

https://github.com/Tanay-ErrorCode/lupo-skill/assets/118350936/f2a46104-e43b-4212-857f-4698f6e7ceae

**Comment by Doraemon012** [comment]
@Ayushmaanagarwal1211 #224 Is already open for this. Closing as duplicate.
