### ISSUE TITLE
feat: UI for article writing

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#230]
### *Is your feature request related to a problem? Please describe.*
Add UI for users to add as well as to read articles.

### *Describe the solution you'd like*
1. Add a link in the navigation bar labeled "Articles" that takes users to the articles section.
2. Create an articles homepage where users can see all the available articles.
3. Add button for creating article.
4. Develop a page where users can write and submit their articles, make it support markdown.

### *Describe alternatives you've considered*
None.

### *Additional context*
- The articles homepage should display article title, author name, author profile image, and publication dates in cards.
- Each article title should be a clickable link that opens the full article.
- The article submission page should include a form with fields for the title, content, and author name.
- A screenshot of a basic wireframe for the articles homepage and submission page is included below.

### Articles homepage:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/508b9f72-6c0e-424e-8b17-8d461ae1b658)

### Writing page:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/17e9c085-cac4-4075-92fc-81f77861f702)

**Comment by nishant0708** [comment]
assign this issue to me

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead !
