### ISSUE TITLE
Add Top to Scroll using react

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Tanay-ErrorCode/lupo-skill#231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
 Implement a "Back to Top" button that allows users to smoothly scroll back to the top of the page when clicked.

**Describe alternatives you've considered**

**Additional context**

**Comment by Doraemon012** [comment]
@VaishnaviMankala19 Our pages are not that long.
