### ISSUE TITLE
bug : Main home page image not set properly for small devices

### ISSUE THREAD

**Issue by mohitmuktikant** [Tanay-ErrorCode/lupo-skill#232]
**Describe the bug**
The main homepage image is not set properly for small devices (below 600px)

**To Reproduce**

1. Go to 'https://lupo-skill.web.app/#/'

**Expected behavior**
In media queries, the minimum width is set till 600px so for small devices like iPhone or samsung (i.e. below 600px), the image overflows

**Screenshots**
![ss13](https://github.com/Tanay-ErrorCode/lupo-skill/assets/101824646/f5cfb7de-2756-4624-81f7-2630e6d16a73)

**Comment by mohitmuktikant** [comment]
@Tanay-ErrorCode so can you assign me this issue under GSSOC'24

**Comment by Doraemon012** [comment]
@mohitmuktikant Go ahead.

**Comment by Tanay-ErrorCode** [comment]
@mohitmuktikant Any updates?

**Comment by mohitmuktikant** [comment]
Yeah I am currently working on it and will try to finish it by tomorrow
