### ISSUE TITLE
feat: adding the  animated cursor.

### ISSUE THREAD

**Issue by happyrao78** [Tanay-ErrorCode/lupo-skill#235]
**Is your feature request related to a problem? Please describe.**
Currently the website  is  looking static so to make it make user interactive I would like  to add the animated cursor in it.

**Describe the solution you'd like**
Will use the react-animated-cursor  library to implement my feature.

**Describe alternatives you've considered**
NA

**Additional context**
Like this  animated cursor
https://github.com/Tanay-ErrorCode/lupo-skill/assets/138770813/4bc082f5-e727-4240-b7b9-ff82d3a7e593

**Comment by Tanay-ErrorCode** [comment]
@happyrao78 Please make trail similar to this (Halley's Comet)

![Halleys-Comet-1986 (1)](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/ef50de50-09a9-44a5-93e2-e76597f93577)

**Comment by happyrao78** [comment]
@Tanay-ErrorCode Kindly assign the level-2 label.

**Comment by Tanay-ErrorCode** [comment]
@happyrao78 Please raise the PR first, level will be assigned after that only.

**Comment by Tanay-ErrorCode** [comment]
@happyrao78 Also, add this effect **only** to the homepage.

**Comment by happyrao78** [comment]
@Tanay-ErrorCode npm install isnt working ? it is taking much longer time as expected though.

**Comment by Tanay-ErrorCode** [comment]
> @Tanay-ErrorCode npm install isnt working ? it is taking much longer time as expected though.

@happyrao78 Depends on connectivity. Delete `.node_modules` folder and run the command again.

**Comment by happyrao78** [comment]
@Tanay-ErrorCode I am facing these errors.
![Screenshot 2024-06-21 094721](https://github.com/Tanay-ErrorCode/lupo-skill/assets/138770813/f2b1725d-d8d8-475e-8732-1c5b9a13e49e)

![Screenshot 2024-06-21 094708](https://github.com/Tanay-ErrorCode/lupo-skill/assets/138770813/a2e0cc55-9302-498f-ae36-ecca4bc9ab40)

**Comment by Tanay-ErrorCode** [comment]
@happyrao78 What version of **node js** and **npm** you are using?

**Comment by happyrao78** [comment]
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/138770813/8705441c-6c5a-42e2-a8e2-a1d60679367a)

**Comment by Tanay-ErrorCode** [comment]
@happyrao78 TypeScript version?

**Comment by Tanay-ErrorCode** [comment]
@happyrao78 Any updates?

**Comment by happyrao78** [comment]
@Tanay-ErrorCode  
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/138770813/7930430a-9eb5-438f-bb88-ae440fcdcb1f)
there are multiple errors like this on your website when I am running the command npm run start.. I have reinstalled the node modules too  but  no  good response.

**Comment by Doraemon012** [comment]
Please refer to [this comment](https://github.com/shadcn-ui/ui/issues/1002#issuecomment-1874619050).

Delete the `node modules folder` and `packageLock.json` then run `npm install`.

**Comment by Doraemon012** [comment]
Please let us know if the issue still persists.

**Comment by Doraemon012** [comment]
@happyrao78 Any updates ?

**Comment by happyrao78** [comment]
> @happyrao78 Any updates ?

Issue not resolved .
