### ISSUE TITLE
feat: Improve the ui of the 'Explore Learning Opportunities' section in home

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Tanay-ErrorCode/lupo-skill#236]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Currently the `Explore Learning Opportunities` section is not attractive.

**Describe the solution you'd like**
I would like to redesign the `Explore Learning Opportunities` section with new eye catching UI with the same content.

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/139672976/a98ed5f0-b6ed-46ac-8666-74276957be33)

**Comment by Tanay-ErrorCode** [comment]
@DharshiBalasubramaniyam Please share your designs according to our website.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Please share your designs according to our website.

OKAY. I'll share.

**Comment by DharshiBalasubramaniyam** [comment]
@Tanay-ErrorCode . Below is my design.


https://github.com/Tanay-ErrorCode/lupo-skill/assets/139672976/ee6ed2dd-c3be-4720-9a3e-9b12c81ca90f

**Comment by Tanay-ErrorCode** [comment]
@DharshiBalasubramaniyam 
- It should be responsive.
- Add more colors. (From `theme.js` or `App.css`)

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam
> 
> * It should be responsive.
> * Add more colors. (From `theme.js` or `App.css`)

It is already responsive. I'll use more colors. Can you please assign this issue to me?

**Comment by Tanay-ErrorCode** [comment]
@DharshiBalasubramaniyam Go ahead, and reduce the speed of the animation too.

**Comment by Tanay-ErrorCode** [comment]
@DharshiBalasubramaniyam Any updates?

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Any updates?

I have raised a pr. Kindly review.
