### ISSUE TITLE
feat: Preloader 

### ISSUE THREAD

**Issue by Jagpreet153** [Tanay-ErrorCode/lupo-skill#237]
**Is your feature request related to a problem? Please describe.**
Yes , adding a preloader will increase user interest in the site 

**Describe the solution you'd like**
I would like to add a responsive preloader animation 

**Describe alternatives you've considered**
It would be completely responsive and matching the theme of the project 

**Additional context**
Kindly assign this task to me under GSSoC'24

**Comment by Tanay-ErrorCode** [comment]
@Jagpreet153 Please make the preloader similar to this.

![spiral-css-preloader](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/edfb82a7-4b75-4d00-8b8d-e81701e46ec7)

**Comment by Tanay-ErrorCode** [comment]
@Jagpreet153 Any updates?

**Comment by Jagpreet153** [comment]
> @Jagpreet153 Any updates?

I am working on it will complete ny tomorrow

**Comment by Doraemon012** [comment]
@Jagpreet153 Any updates?

**Comment by Jagpreet153** [comment]
Sorry @Doraemon012 . I will complete it soon

**Comment by Doraemon012** [comment]
@Jagpreet153 Any updates?

**Comment by Tanay-ErrorCode** [comment]
Unassigning as inactive.

**Comment by AryanPahuja21** [comment]
@Tanay-ErrorCode please assign this issue to me under GSSoC'24

**Comment by Tanay-ErrorCode** [comment]
@AryanPahuja21 Go ahead.
