### ISSUE TITLE
feat: "Style the Vertical Scrollbar" Matching to "Website Design" theme

### ISSUE THREAD

**Issue by MastanSayyad** [Tanay-ErrorCode/lupo-skill#238]
Hey @Tanay-ErrorCode and @Doraemon012 

**Is your feature request related to a problem? Please describe.**

The website has a vertical scrollbar which needs some styling to look more eye-catching and visually appealing

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/101971980/accf0ef1-2b40-4665-9384-c3700bcf2835)

**Describe the solution you'd like**

Style vetical scrollbar matching to the website design theme

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by MastanSayyad** [comment]
@Tanay-ErrorCode and @Doraemon012 could you please assign me this issue!!

**Comment by Tanay-ErrorCode** [comment]
@MastanSayyad Please make scrollbar similar to this, specially check the hover effect. This is firefox default scrollbar.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/564f4f60-cd20-4e06-8534-52656486a69c
