### ISSUE TITLE
feat: Improve the UI of navbar

### ISSUE THREAD

**Issue by Yash-Ainapure** [Tanay-ErrorCode/lupo-skill#240]
**Is your feature request related to a problem? Please describe.**
I would like to make the navbar transparent glass like texture and more attractive than present

**Describe the solution you'd like**
Making the navbar translucent type make make it look like a modern website

**Describe alternatives you've considered**
You could suggest something if required

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/136250383/36265789-ba39-42c8-b490-d93c0b16e54f)
this is the present UI of navbar

please assign me the issue ,so that i could start the work

**Comment by Tanay-ErrorCode** [comment]
@Yash-Ainapure Do you mean this kind of effect?

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/48400d77-2aa2-40b2-b8b4-7f5f685d8146)

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Do you mean this kind of effect?
> 
> ![image](https://private-user-images.githubusercontent.com/90561803/341511529-48400d77-2aa2-40b2-b8b4-7f5f685d8146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5OTI4OTcsIm5iZiI6MTcxODk5MjU5NywicGF0aCI6Ii85MDU2MTgwMy8zNDE1MTE1MjktNDg0MDBkNzctMmFhMi00MGIyLWI4YjQtN2Y1ZjY4NWQ4MTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE3NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYWM4MmQxNzQxMTJhMGNhZmI0MDE4MDI1ZDdjNmZiYTEwNzU1ZWMyNjFjMDdmMTgzNjVkNWU4MWEwODA0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ClsQ-TobH-x951mPIzpzO8b6mnZpVMs4JThB2yVNyko)

Yes, bit similar to this

**Comment by Doraemon012** [comment]
@Yash-Ainapure We already have a the effect.
