### ISSUE TITLE
feat: Enhancing the landing page by eliminating the white spaces 

### ISSUE THREAD

**Issue by Amruta7203** [Tanay-ErrorCode/lupo-skill#244]
**Is your feature request related to a problem? Please describe.**

There are unwanted white spaces in the landing page:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116087736/662873e1-92c5-4636-83bb-2255fd41d2df)

the space above the main heading is disturbing the overall look of the landing page 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Amruta7203 Ok, go for it.
