### ISSUE TITLE
bug : missing copyright in the footer 

### ISSUE THREAD

**Issue by Amruta7203** [Tanay-ErrorCode/lupo-skill#246]
**Describe the bug**
Copyright statement is missing in the footer 

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116087736/6029204f-f8a4-4c7e-bb0e-23dc4d36d257)

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Amruta7203 We do not need this. Instead of it add link to my [YouTube channel](https://www.youtube.com/channel/UCN7Lo2yjOFomJLDpAxxcSMw) to the footer.
