### ISSUE TITLE
bug : Issue in create event page 

### ISSUE THREAD

**Issue by Amruta7203** [Tanay-ErrorCode/lupo-skill#247]
**Describe the bug**

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116087736/4578a664-b4aa-4467-8d54-5e7d53a80f63)

The create event page heading is not placed properly, also the gap between field elements is uneven

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116087736/415ac17c-08ef-4c46-8ab0-1c6b80e46663)

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Amruta7203 There is already a PR for this #233
