### ISSUE TITLE
bug : missing git pull command in contributing.md file

### ISSUE THREAD

**Issue by Amruta7203** [Tanay-ErrorCode/lupo-skill#253]
**Describe the bug**

The contributing.md file is missing crucial git remote upstream and git pull command. This command ensures that the changes are made in the updated code thereby eliminating conflicts.

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Amruta7203 We do not need this.
