### ISSUE TITLE
feat: Creating a 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Tanay-ErrorCode/lupo-skill#257]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/125277258/b6c8d011-e4e1-488a-8143-fe9a56aa245f)

**Describe the solution you'd like**
we can add some error image and gifs

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@RamakrushnaBiswal 404 page is already there as seen in the screenshot.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/fd7c9f87-5731-451a-8179-04e381012169)

---

But there is a bug, when going on event details page, if the event id is wrong, only a toast displays for now, but it should show 404 page. Can you fix this?

**Comment by RamakrushnaBiswal** [comment]
hi @Tanay-ErrorCode we need to add this i guess 
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/125277258/003f7500-5d1d-42b3-bf67-d52e5ea9360c)
https://firebase.google.com/docs/hosting/full-config#404


the configured error page is working for unknown URL but for deploying purpose we need to create another one

**Comment by Tanay-ErrorCode** [comment]
@RamakrushnaBiswal The application uses **HashRouter** so if there is wrong URL after the `/#/`, then it will display the 404 page. This is the current functionality, but if there is something other than `#`  entered by user, it displays that **firebase 404 page** 

Make 404 page (html one) similar to the current one and fix that event details bug too.

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/125277258/cb7aaa7e-769a-49ab-a3e2-964526555a0b)

**Comment by RamakrushnaBiswal** [comment]
hi @Tanay-ErrorCode  we need to change the `start url` in build directory

**Comment by Tanay-ErrorCode** [comment]
> hi @Tanay-ErrorCode we need to change the `start url` in build directory you can change and check the deploy

@RamakrushnaBiswal Instead of this, it can be done using **[this process](https://firebase.google.com/docs/hosting/full-config#404)**

**Comment by RamakrushnaBiswal** [comment]
@Tanay-ErrorCode for this we need to change directory to public

**Comment by Tanay-ErrorCode** [comment]
@RamakrushnaBiswal There is already a public directory (in which there is `index.html`), you have to create `404.html` there, it will work fine.

**Comment by RamakrushnaBiswal** [comment]
ok i will create

**Comment by Tanay-ErrorCode** [comment]
> ok i will create the same design or new one for the page @Tanay-ErrorCode

Same.
