### ISSUE TITLE
[Feature] : Navbar mobile site

### ISSUE THREAD

**Issue by sivaprasath2004** [Tanay-ErrorCode/lupo-skill#258]
Hello @Tanay-ErrorCode 
-  In this project `Nav bar` mobile site it's like so simple.
- In this `Navbar` it so small .

### Actual work
 
![Screenshot from 2024-06-23 08-27-48](https://github.com/Tanay-ErrorCode/lupo-skill/assets/121082414/d69a0ac7-90dd-4f18-b432-0b8da9b814be)

### My work

[Screencast from 2024-06-23 08-25-53.webm](https://github.com/Tanay-ErrorCode/lupo-skill/assets/121082414/a5241254-6f7b-4fea-b22d-77cfff51b597)

**Comment by Tanay-ErrorCode** [comment]
@sivaprasath2004 Go ahead. Use **[MUI drawer](https://mui.com/material-ui/react-drawer/)** and in the drawer open view **do not** center the elements.
