### ISSUE TITLE
feat: Add support for article writing (backend)

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#261]
### **Is your feature request related to a problem? Please describe.**
Currently, there is UI for **Article Writing**, add backend logic to create and display articles.

### **Describe the solution you'd like**
* The files for article writing pages are already there, add the functionality to write articles in `ArticleWritingPage.tsx`.
* Write the functionality to fetch and display all articles form the firebase RTDB, the file is `Articles HomePage.tsx`.
* Add the functionality to fetch content from single article and display it, create UI for this page.

### **Describe alternatives you've considered**
None.

### **Additional context**

The single article reading page should look like this:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/08be3840-a846-4fdc-8868-a0a23bfcfa66)

The data must be stored this this way:

* There must be another section in the database named **`articles`**:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/16440ba0-af14-410a-b114-31b4657e2827)

* Inside articles the articles will be saved with a unique ID like the events:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/9d217597-2e0e-4c53-aaf8-89c15ab46ba9)

* The unique Id generation function used must be:
``` typescript

function generateUUID() {
  var d = new Date().getTime();
  var d2 =
    (typeof performance !== "undefined" &&
      performance.now &&
      performance.now() * 1000) ||
    0;
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
    var r = Math.random() * 16;
    if (d > 0) {
      r = (d + r) % 16 | 0;
      d = Math.floor(d / 16);
    } else {
      r = (d2 + r) % 16 | 0;
      d2 = Math.floor(d2 / 16);
    }
    return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
  });
}
```

**Comment by nishant0708** [comment]
Assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
