### ISSUE TITLE
feat: change the background of the event page and make like main page 

### ISSUE THREAD

**Issue by heli0707** [Tanay-ErrorCode/lupo-skill#262]
add the same background as the main page on the events page 

**Is your feature request related to a problem? Please describe.**
the event page is not looking good 

assign this issue to me!
I want to work on this issue as a GSSoC 24 contributor

**Comment by Doraemon012** [comment]
@heli0707 We do not need this.

**Comment by Doraemon012** [comment]
@heli0707 Please feel free to take up any other open issues, or open one by yourself if needed.
