### ISSUE TITLE
feat: Add Social media Links In the footer

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Tanay-ErrorCode/lupo-skill#266]
**Is your feature request related to a problem? Please describe.**
Adding soical Media Links in the footer 

**Describe the solution you'd like**
Adding soical Media Links in the footer 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Saipradyumnagoud** [comment]
@Tanay-ErrorCode Please assign me the issue

**Comment by Tanay-ErrorCode** [comment]
@Saipradyumnagoud We do not have much social media links. And the ones we have are already added. Please take a look at other issues.

**Comment by Saipradyumnagoud** [comment]
@Tanay-ErrorCode Adding links like instagram linkedin Youtube And git hub i hope this will be help ful
