### ISSUE TITLE
bug :Remove unnecessary gap

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Tanay-ErrorCode/lupo-skill#267]
Hey @Tanay-ErrorCode  . I am a GSSoC'24 Contributor.

I'd like to contribute to your project by removing unnecessary gaps in footer in events page in mobile view 
Kindly assign this issue to me.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/142687709/f51cfd43-56d8-4043-980f-c58672967c8e)

**Comment by dhairyagothi** [comment]
> Haha @Khushi-Pushkar Wrong repo i guess XD

It's your repo only check footer

**Comment by pooranjoyb** [comment]
Nope my repo is [Popshop](https://github.com/pooranjoyb/popShop) and this is something else :/
