### ISSUE TITLE
bug :  dark and light mode toggle is not working

### ISSUE THREAD

**Issue by reshamsai150** [Tanay-ErrorCode/lupo-skill#268]
**Describe the bug**
dark and light mode toggle is not working 

**To Reproduce**

**Expected behavior**
when clicked on button it should shift to dark/light mode  but its not working

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/164533685/bff9bfa3-bc19-4d8b-a844-77e3715f606d)

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@reshamsai150  Let all the pages be redesigned. Then we will open dark mode issues. Closing as not planned.
