### ISSUE TITLE
feat: add scroll to top feature button

### ISSUE THREAD

**Issue by reshamsai150** [Tanay-ErrorCode/lupo-skill#269]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
user has to manually scroll website to reach home page

**Describe the solution you'd like**
it can reduce the manual work and automates the work

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@reshamsai150 Our pages are not that long.
