### ISSUE TITLE
feat: add github  automatic greeting bot

### ISSUE THREAD

**Issue by reshamsai150** [Tanay-ErrorCode/lupo-skill#270]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@reshamsai150 Thanks for opening the issue, but we do not intend to enhance GitHub but our application, please take a look at other issues.
