### ISSUE TITLE
bug : Profile Page is not displaying

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#271]
**Describe the bug**

**To Reproduce**

1. Login in the app.
2. Click on profile icon in navbar
3. Click on view profile.
4. See the error.

**Expected behavior**
On opening the profile of a person, it should display correctly without giving any error.

**Screenshots**
<video src="https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/67c71514-118a-4216-8303-d4f05ea1387f"/>

**Additional context**
None

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Maybe it is caused by #215 . Kindly fix this.

**Comment by nishant0708** [comment]
Okay

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  i checked it is working Fine in my system and i checked my fork is also up-to-date

**Comment by Tanay-ErrorCode** [comment]
> hey @Tanay-ErrorCode i checked it is working Fine in my system and i checked my fork is also up-to-date

@nishant0708 This is happening for the person who has set social media profile links on profile. For more information, checkout the video I provided or create a new account. Set social media links by **edit profile**.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  see this am i doing something wrong?
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/cb2a765e-fc21-432a-9ec3-f47e4deff92e

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Ok there was some misunderstanding due to old account (functionality updated after i set the links.)
