### ISSUE TITLE
feat: Update react-router-dom to version 6 and refactor routing logic

### ISSUE THREAD

**Issue by MinavKaria** [Tanay-ErrorCode/lupo-skill#273]
**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.
- Changing normal router as hash router creates difficulties in SEO 

_GSSOC'2024 Contribuitor_

@Tanay-ErrorCode assign this to me.

**Comment by Doraemon012** [comment]
@MinavKaria Go ahead.

**Comment by MinavKaria** [comment]
Sry for delay, I'll send the PR tomorrow

**Comment by MinavKaria** [comment]
@Doraemon012 Have sent the PR check

**Comment by MinavKaria** [comment]
@Doraemon012 Please acknowledge
