### ISSUE TITLE
bug : Even after registering for event, button shows register, instead should show registered

### ISSUE THREAD

**Issue by Joyosmit** [Tanay-ErrorCode/lupo-skill#28]
**Describe the bug**
Even after registering for event, button shows register, instead should show registered

**To Reproduce**
1. Go to '/dashboard or /events'
2. Click on 'Register'
3. It shows toast that regsitered but button still shows 'Register'

**Expected behavior**
Button should be showing Registered

**Comment by Tanay-ErrorCode** [comment]
@Joyosmit You can start working on this.

**Comment by Joyosmit** [comment]
Alright will get started on it
