### ISSUE TITLE
feat: Adding Loader and Animation to the event cards 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Tanay-ErrorCode/lupo-skill#282]
**Is your feature request related to a problem? Please describe.**
When i am changing the filters then the cards will be directly removed or shown which doesn't looks good i want to add a 1s loader so that it will create an effect like it is loading the cards and also on changing the filters i want to add the coming animation on the cards .

**Describe the solution you'd like**
I want to add the loader and adding animations after user change the filter  to the cards

https://github.com/Tanay-ErrorCode/lupo-skill/assets/118350936/c9ac0c34-694f-4598-b7b4-a34b87a49009

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 What kind of animation should it be having ? Add some screen recordings of animation.

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/Tanay-ErrorCode/lupo-skill/assets/118350936/37daefdf-b21e-4556-a5c1-2b8ade398ff8

@Tanay-ErrorCode  I want to add this type of animation  or i can add any other as well according to you

**Comment by Tanay-ErrorCode** [comment]
@Ayushmaanagarwal1211 Add a **Fade in** and **Fade Out** animation.

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Can you work on this?

**Comment by nishant0708** [comment]
Yes

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
