### ISSUE TITLE
Floating animation to the Home page image

### ISSUE THREAD

**Issue by Damini2004** [Tanay-ErrorCode/lupo-skill#283]
**Is your feature request related to a problem? Please describe.**
Home image is not attractive to for enhancing user engagement.
**Describe the solution you'd like**
Adding floating animation to the image for tempting look
**Describe alternatives you've considered**
**Additional context**
![Screenshot 2024-06-28 124827](https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/c89b0255-701b-44bc-b67f-05a18fb005de)

**Comment by Tanay-ErrorCode** [comment]
We do not need this. You can take up any other open issues, or open one by yourself if needed.
