### ISSUE TITLE
feat: Dynamic title display on article reading page

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#285]
### **Is your feature request related to a problem? Please describe.**
Currently when we view any article in the website, its title is **`Articles | Lupo Skill`,** it should display the article title, and the article writer name.

### **Describe the solution you'd like**
**`{Titleof the article} | by {Writer Name} | Lupo Skill`**, This should be title of the page.

### **Describe alternatives you've considered**
None

### **Additional context**
None

**Comment by nishant0708** [comment]
@Tanay-ErrorCode  assign me this issue

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead.
