### ISSUE TITLE
bug : Image overflowing the the article

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#286]
### **Describe the bug**
If we create an article with image (markdown supported) whose width is more than the card, it overflows when reading the article.

### **To Reproduce**

1. Go to Articles page
2. Click on any article title.
3. Scroll down to any image
4. See the image coming out of the card.

### **Expected behavior**
The image should not go out of the card.

### **Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/50c7046a-2733-47d3-a971-9526a7d6f13e)

### **Additional context**
None

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode Assign me this issue

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead.
