### ISSUE TITLE
feat: Opening writer profile from the article reading page.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#287]
**Is your feature request related to a problem? Please describe.**
Currently we can't visit the profile of the writer of the article. We need this basic functionality.

**Describe the solution you'd like**
On clicking either the Profile picture of user or on the name, it should open the profile of that user (The same functionality is in the event card.).

**Describe alternatives you've considered**
None

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/6389d3a8-5d83-468d-a3fc-6efcc5f9df86)

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
