### ISSUE TITLE
feat: Floating animation in home page

### ISSUE THREAD

**Issue by Damini2004** [Tanay-ErrorCode/lupo-skill#292]
**Is your feature request related to a problem? Please describe.**
Tempting effect
**Describe the solution you'd like**
User engagement increase
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/ab64dc43-611f-4e22-890a-f9847aafc5e6)

**Comment by Doraemon012** [comment]
We do not need this. @Damini2004
