### ISSUE TITLE
feat: Want to Make Clap/Like count functional in Article page

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#295]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Currently Like Functionality is not working in Article section I will make it work

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Doraemon012** [comment]
@nishant0708 Go ahead!
