### ISSUE TITLE
Newsletter section addition

### ISSUE THREAD

**Issue by Damini2004** [Tanay-ErrorCode/lupo-skill#297]
**Is your feature request related to a problem? Please describe.**
subscription model 
**Describe the solution you'd like**
subscription model 

**Describe alternatives you've considered**
subscription model 

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/119414762/de87f075-0f07-4969-9c25-8caa48f64c57)

**Comment by Doraemon012** [comment]
@Damini2004 We do not need this. You can take up any other open issues, or open one by yourself if needed.
