### ISSUE TITLE
Profile can  not be edited in settings

### ISSUE THREAD

**Issue by Ankesh2004** [Tanay-ErrorCode/lupo-skill#3]
Profile is not being updated from settings.
Bug Video :  https://jmp.sh/tDgdCcvo

Kindly assign me this issue under GSSOC'24

**Comment by Tanay-ErrorCode** [comment]
@Ankesh2004 Please give a video or screenshots to help explain your problem.

**Comment by Ankesh2004** [comment]
> @Ankesh2004 Please give a video or screenshots to help explain your problem.

@Tanay-ErrorCode  I have updated the previous comment, please check

**Comment by Tanay-ErrorCode** [comment]
@Ankesh2004 Please clarify your approach to fix this.

**Comment by Tanay-ErrorCode** [comment]
@Ankesh2004 According to GSSoC guidelines, only the contributions after 10 May 2024, 7 PM IST will be considered.
I am closing this issue, You have to open another issue for this.

**Always use the template for creating issues and PRs.**
