### ISSUE TITLE
feat: Sort events by `createdAt`

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#30]
##  **Is your feature request related to a problem? Please describe.**
Currently, the events in our website are not sorted, making it difficult for viewers to quickly find relevant events.

## **Describe the solution you'd like**
The events on our website should appear in sorted order by default. This means that when users visit the `events page`, `dashboard page` or the `user profile page`, they will see the events already sorted according to the `createdAt` time. 

### **Pages to be affected**
- Events Page
- Dashboard Page
- User Profile Page

## **Describe alternatives you've considered**
None

**Additional context**
No additional context.

**Comment by sahilhedau49** [comment]
Please assign me this issue. I will be happy to complete it.

**Comment by Doraemon012** [comment]
@sahilhedau49 You can now work on this.

**Comment by sahilhedau49** [comment]
@Doraemon012 Can you provide a snapshot of events Database.

**Comment by Doraemon012** [comment]
@sahilhedau49 

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/fd5631ba-68a6-46a4-bb3a-f1d8d00b8876)
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/13046a62-2690-4aa8-af2f-70ac552451d4)

You can create your own events database in Firebase. If you've linked your website to Firebase on your computer, you can create events directly from the website running locally on your machine. These events will then be stored in your personal Firebase database.

If you have problem setting up firebase, go through [the docs](https://firebase.google.com/docs/web/setup). Follow the step 1 and then paste the firebase config in `src/firebaseConf.ts`

**Note: When you will make a PR, do not push your firebaseConfig.**
