### ISSUE TITLE
bug : If User is Not Logged In Then Signup Model should comeup in Create Event

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#300]
**Describe the bug**

**To Reproduce**

1. logout
2. Click on 'create event'

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Display it instead of the **Please login first** toast.
