### ISSUE TITLE
bug : Date Picker Overlapping Event Tags  + Cant scroll Down in `Create event` in Mobile Screen

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#301]
**Describe the bug**

**To Reproduce**

1. Go to 'create events'
2. Click on 'datepicker'

![Screenshot 2024-07-04 035956](https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/dca77534-0ecd-4f14-b012-c3aae9124940)
![Screenshot 2024-07-04 040003](https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/ded21f9e-cb84-47a5-b843-38f8f44c5435)

**Cant Scroll Create Event Page in Mobile View**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 

1. Use **[MUI datepicker](https://mui.com/x/react-date-pickers/date-picker/#basic-usage)** instead of current one.
2. Use **[MUI timepicker](https://mui.com/x/react-date-pickers/time-picker/#basic-usage)** instead of current one.
