### ISSUE TITLE
feat: Handling click on the article homepage

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#302]
**Is your feature request related to a problem? Please describe.**
Currently we can open the article only by clicking on the title, we need to change this. Also, there is no functionality to open the writer profile from the article homepage.

**Describe the solution you'd like**
1. On clicking on the writer name or profile image, the profile must open.
2. On clicking on the card, the article must open.

**Describe alternatives you've considered**
None.

**Additional context**
1. When the user clicks on the **red part**, writer profile image must open.
2. When the user clicks inside the **orange part**, the article must open.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/7dc4070d-5d91-42d6-898d-2bccf5039736)

**Comment by tkshsbcue** [comment]
@Tanay-ErrorCode i would like to work on this issue

**Comment by Tanay-ErrorCode** [comment]
@taksabke Ok go ahead. Already there is functionality to go to user profile by clicking on the profile picture or writer name. Create card click functionality.

**Comment by tkshsbcue** [comment]
@Tanay-ErrorCode i was just all the features are working so there is nothing to be fix ig

**Comment by Doraemon012** [comment]
@tkshsbcue 

Currently, we can open the author's profile by clicking on the author's name, whereas the article page is only opening when we click on the article title (not the other parts of the card).

[Screencast from 07-04-2024 09:17:27 AM.webm](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/c1783d7d-c238-4127-a671-65c2044dbdd5)

We need a functionality like [this](https://medium.com/):

[Screencast from 07-04-2024 09:23:07 AM.webm](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/ae8c83e6-adca-4c2f-9a59-7224a0883c92)

**Comment by tkshsbcue** [comment]
okay got it

**Comment by tkshsbcue** [comment]
@Tanay-ErrorCode i have made a PR request along with i have also attached the video of it working please have a look into it

**Comment by tkshsbcue** [comment]
@Doraemon012 i have made a PR request along with a video have a look into it
