### ISSUE TITLE
bug : [Add title here] toggle button is not working

### ISSUE THREAD

**Issue by prachita0504** [Tanay-ErrorCode/lupo-skill#306]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@prachita0504 We have not designed the dark theme yet.

**Comment by Tanay-ErrorCode** [comment]
@prachita0504 Please take up any other issue.
