### ISSUE TITLE
feat: Add Right and Left Arrow Buttons in User Review Slider

### ISSUE THREAD

**Issue by Saksham2k3s** [Tanay-ErrorCode/lupo-skill#309]
**Is your feature request related to a problem? Please describe.**
Currently, the user review slider component lacks navigation buttons to allow users to easily navigate between reviews. Adding right and left arrow buttons will enhance user experience by providing intuitive navigation controls.

**Describe the solution you'd like**
Feature: Introduce right and left arrow buttons.
Functionality: Enable users to navigate forward and backward through user reviews.
Component: Implement within the UserReviewSlider component.
Icons: Utilize icons like FaChevronLeft and FaChevronRight for the arrow buttons.

**Describe alternatives you've considered**
Users can click the right arrow to move to the next review.
Users can click the left arrow to move to the previous review.
Wrap-around functionality: If at the end of the reviews, clicking right moves to the first review, and vice versa.

**Additional context**

**Comment by Doraemon012** [comment]
@Saksham2k3s We do not need this.
