### ISSUE TITLE
bug: Updating the logic for profile pictures

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#317]
**Is your feature request related to a problem? Please describe.**
For first-time accounts, the profile picture(url) is set to the Google profile picture. If a user creates an article and then updates their profile picture using the edit profile button, the image in the article does not change. We need to fix this.

**Describe the solution you'd like**
When a user updates their profile picture, any articles they have created should automatically update to show the new profile image.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by nishant0708** [comment]
Assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
