### ISSUE TITLE
feat: Add option to share event

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#318]
### **Is your feature request related to a problem? Please describe.**
Currently, there is no functionality to share events. We need to add this functionality to the event details page.

### **Describe the solution you'd like**
Add a share button **only** on the **event details page**.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/bc990612-2aaf-422a-a6e2-ae817e3c9122)

Upon clicking the share button, a modal like the image below should open.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/0429c394-1b9f-4dd6-ba9b-26c3c04168c2)

### **Describe alternatives you've considered**
None

### **Additional context**
None

**Comment by nishant0708** [comment]
Assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
