### ISSUE TITLE
bug : All users should be able to read the articles

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#319]
**Describe the bug**
If we are not logged in, on clicking on articles in navbar, it prompts us to signIn or login.

**To Reproduce**

1. Click on Articles in the navbar
2. See prompt

**Expected behavior**
The logged out users must be able to read the articles.

**Screenshots**
None

**Additional context**
If clicked on create article, then the prompt must appear.

**Comment by devansh-dek** [comment]
Can I work on the issue?

**Comment by Tanay-ErrorCode** [comment]
@devansh-dek Go ahead.
