### ISSUE TITLE
feat: Add edit article feature

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#324]
### **Is your feature request related to a problem? Please describe.**
Currently, users do not have the ability to edit articles once they have been published. This can lead to issues if there are errors or updates needed for the content.

### **Describe the solution you'd like**
* Implement an "Edit Article" feature that allows users to modify the content of their published articles.

* Add an edit button in the article reading page, that should be visible only when creator is viewing the article.

### **Describe alternatives you've considered**
None

### **Additional context**

The articles are stored in this way:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/bf127a9a-0dd8-4bde-9ca3-9d8904b15719)

**Comment by devansh-dek** [comment]
Can i work on this?

**Comment by nishant0708** [comment]
Can i work on this @Tanay-ErrorCode

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012 can I work on this

**Comment by Tanay-ErrorCode** [comment]
@devansh-dek Please describe your approach.

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode when user clicks on edit what should happen like you need modal or something else please let me know

**Comment by Tanay-ErrorCode** [comment]
@nishant0708
- In the article reading page a **pencil icon (MUI)** must appear **only when user is the creator**

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/cd8b362f-4dfc-48ed-a310-dcfefd88f64d)

- On clicking on the button the page should redirect to `.../#/editArticle/{articleId}`. This page will be the same as create article page. 
- The data (title and the description) **must only be passed through props**.
- The current data must be already filled on the edit page.
