### ISSUE TITLE
bug : Event Showing Expired even when it is not expired

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#327]
**Describe the bug**
Event Showing Expired even when it is not expired

**To Reproduce**

1. Go to 'create events'
2. create new events
3. go to events

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/12d86ab8-1592-406d-b034-480c5df7899b)

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
