### ISSUE TITLE
feat: Adding event page

### ISSUE THREAD

**Issue by PranotiPD** [Tanay-ErrorCode/lupo-skill#329]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think it would be a great user experience if we could show more details about the event, And also, providing an option for users to ask their queries. So when the user clicks on a particular event he/she will be redirected to that events page where they will get to know more about the event. ask questions or simply leave a review of that event if they attend it, or like give rating to the event.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@PranotiPD The page is already there.
