### ISSUE TITLE
bug : Removing pagination when there is no content

### ISSUE THREAD

**Issue by PranotiPD** [Tanay-ErrorCode/lupo-skill#330]
**Describe the bug**
When there is only a single page or no content available we can avoid showing pagination.

**Expected behavior**
below screenshot

**Screenshots**
![Screenshot (781)](https://github.com/Tanay-ErrorCode/lupo-skill/assets/97724414/da016703-1b96-4024-a844-6fa3b2a5c9de)

**Additional context**
For instance in the above example, we can avoid showing that 1 there.

**Comment by Tanay-ErrorCode** [comment]
@PranotiPD Go ahead.
