### ISSUE TITLE
Add Lisence.md

### ISSUE THREAD

**Issue by ananyag309** [Tanay-ErrorCode/lupo-skill#332]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
 The `license.md` file is essential for specifying the usage rights and legal terms for the project, ensuring compliance, clarity, and protection for both creators and users.  

**Describe the solution you'd like**
 Creating a `license.md` file in the repository of an open-source program is crucial as it defines how others can use, modify, and distribute the code, ensures legal compliance, clarifies expectations for contributors and users, and provides a level of protection for both the project maintainers and users.  

**Describe alternatives you've considered**

**Additional context**
 I want to create the `license.md` file to ensure legal compliance and clarify the terms of use for our open-source project. this is generally present in all repo

**Comment by Tanay-ErrorCode** [comment]
@ananyag309 We do not intend to enhance our github. Please take up other issues or open one yourself.
