### ISSUE TITLE
Enhance Readme.md

### ISSUE THREAD

**Issue by ananyag309** [Tanay-ErrorCode/lupo-skill#333]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I am aiming to enhance readme.md by adding table of content, feature in section (i have added it's ss), link learn.md in main readme file etc.

I am not going to add the same feature in section but a more better one, this will make readme look much more better.
![readmee](https://github.com/Tanay-ErrorCode/lupo-skill/assets/145869907/a62ce3f0-6b4a-4933-8851-270d342f82e3)

**Describe the solution you'd like**
 Enhancing the README file is important because it serves as the first point of contact for potential users and contributors, providing crucial information about the project, its purpose, how to use it, and how to contribute. A clear and informative README can attract more users and collaborators while also helping them understand the project quickly and effectively.  

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@ananyag309 We do not intend to enhance our github. Please take up other issues or open one yourself.
