### ISSUE TITLE
Adding contents of header to footer

### ISSUE THREAD

**Issue by AkshitGarg24** [Tanay-ErrorCode/lupo-skill#334]
**Is your feature request related to a problem? Please describe.**
The footer lacks the contents of the header.

**Describe the solution you'd like**
A separate section should be made in the footer which includes contents like Home, dashboard, events, articles and create event.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Tanay-ErrorCode** [comment]
@AkshitGarg24 Please provide an image to be more clear.

**Comment by Tanay-ErrorCode** [comment]
@AkshitGarg24 We do not need this. Please take up other issues or open one yourself if needed.
