### ISSUE TITLE
feat: Share option for articles.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#336]
**Is your feature request related to a problem? Please describe.**
Add share option for articles, users should be able to share particular article.

**Describe the solution you'd like**
We have the functionality to share events, create functionality to share the articles.

**Describe alternatives you've considered**
None.

**Additional context**
Share icon must be placed here:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/9a5037a0-6add-4a3f-9880-7237bbe3c6fa)

The share popup should look like:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/2cb54791-41c1-4b82-8084-23a5aec24a8d)

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode  please assign me this issue

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode can I work on issue 324 as other guy is not responding?
