### ISSUE TITLE
bug : Every line in article content is truncated

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#337]
**Describe the bug**
Every line in article content is truncated by `...`.

**To Reproduce**
1. Open Lupo Skill on smaller screen (Tablet/Mobile)
2. Go to `Articles`
3. Open an Article
4. Read the article content
5. Notice that every line in the article content is truncated by `...`

**Expected behavior**
The text in article should not be truncated, it should be visible as it appears on larger screens.

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/03f4fc21-9af0-4360-ba97-515e236abf41)

**Additional context**
None.

**Comment by nishant0708** [comment]
hey @Doraemon012 @Tanay-ErrorCode assign me this issue
