### ISSUE TITLE
feat: Search Functionality and Filter of events

### ISSUE THREAD

**Issue by Poushik11** [Tanay-ErrorCode/lupo-skill#34]
**Is your feature request related to a problem? Please describe.**
Implement advanced search and filtering options to help users find relevant events more easily. 

**Describe the solution you'd like**
Allow filtering by date, location, skill level, and type of event 

**Describe alternatives you've considered**

**Additional context**

**Comment by Poushik11** [comment]
Hello @Doraemon012

Please assign the issue to me

**Comment by PuR-vI** [comment]
Please assign this to me

**Comment by Tanay-ErrorCode** [comment]
@Poushik11 

The filter options should be:
- Upcoming Events
- Ongoing Events
- Past Events

i.e. filter on the basis of time

Do not add a filter for
- location as all the events are supposed to be online
- Skill level as there is no such field
- Type of event as there is no such field

Also, please wait till the front end is ready or follow up with issue #24 (it addresses the front end for event filtering)

**Comment by Tanay-ErrorCode** [comment]
> Please assign this to me

@PuR-vI We assign issues on a first-come-first-serve basis. Please feel free to take up any other issues in the repo.

**Comment by Poushik11** [comment]
Sure I was just suggesting will do the changes on  Upcoming Events
Ongoing Events
Past Events

**Comment by Tanay-ErrorCode** [comment]
@Poushik11 You need to add the search bar in the navbar.

**Comment by Poushik11** [comment]
@Tanay-ErrorCode Yes sure

**Comment by Tanay-ErrorCode** [comment]
@Poushik11 Any updates?

**Comment by Poushik11** [comment]
Sorry @Tanay-ErrorCode will complete this by Today 🙏
