### ISSUE TITLE
Add Icons to Navbar

### ISSUE THREAD

**Issue by sailaja-adapa** [Tanay-ErrorCode/lupo-skill#340]
Hello Project Admin
I would like to add icons to Navbar to make website look attractive
Can you assign me this issue under GSSOC'24

![IMG_20240710_214509](https://github.com/Tanay-ErrorCode/lupo-skill/assets/161804629/0c476230-8d20-42b2-a6c5-5f09150d9c63)

**Comment by Tanay-ErrorCode** [comment]
@sailaja-adapa We do not need to add icons to the navbar for now. Please take up another issue or open one yourself if needed.

**Comment by sailaja-adapa** [comment]
Yeah okk @Tanay-ErrorCode
