### ISSUE TITLE
bug : Like Button Not Clickable

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#345]
**Describe the bug**

**To Reproduce**

1. Go to 'artticlehomepage'
2. Click on 'clap icon'
3. See error

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/8ab5d20f-7b51-4186-b002-036da1fa6daa)

**Additional context**

**Comment by Doraemon012** [comment]
@nishant0708 This is intentional, if the user clicks on the card, it should go to the article reading page.
