### ISSUE TITLE
Adding License

### ISSUE THREAD

**Issue by mahek0620** [Tanay-ErrorCode/lupo-skill#346]
**Is your feature request related to a problem? Please describe.**
Currently, the project lacks a clear license, which creates uncertainty for contributors and users regarding their rights and obligations when using, modifying, or distributing the code.

**Describe the solution you'd like**
Add a LICENSE file to the project repository, clearly stating the terms under which the project's code can be used, modified, and distributed. Consider using a widely recognized open-source license such as MIT

**Additional context**
Adding a license will help clarify the legal standing of the project, encourage more contributions, and ensure users understand their rights.

**Comment by Tanay-ErrorCode** [comment]
@mahek0620 We do not need this. Take up another issue or open one yourself if needed.
