### ISSUE TITLE
feat: `createEvent` cannot  publish

### ISSUE THREAD

**Issue by sivaprasath2004** [Tanay-ErrorCode/lupo-skill#347]
**Is your feature request related to a problem? Please describe.**
- In this project `/createEvent` page I'll filled the all details but it can't publish .

**Describe the solution you'd like**
- If the all fields can be filled after the event can be publish this is use expected.

**Describe alternatives you've considered**

[Screencast from 2024-07-13 20-45-23.webm](https://github.com/user-attachments/assets/fa08dd36-a99f-4174-b4f9-6f45733d2863)

**Additional context**
- please assign me..

**Comment by Tanay-ErrorCode** [comment]
@sivaprasath2004 You have to hit the enter button when you enter tags. Please take up another issue or create one yourself if needed.
