### ISSUE TITLE
feat: Alert on unpublished events, articles.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#352]
**Is your feature request related to a problem? Please describe.**
When writing an article or creating an event, users may lose their changes if they navigate to another page without publishing.

**Describe the solution you'd like**
Show an alert message when a user tries to leave the page without publishing. The message should say, "Your changes have not been saved. Are you sure you want to leave this page?"

**Describe alternatives you've considered**
None.

**Additional context**
This feature will help prevent data loss and ensure users save their changes before leaving the page.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode can i work on this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012   i tried to solve this i use many approaches like  tried to use Prompt of react-router-dom  even tried react-router-prompt and everything its kinda not working . Can you please tell me like What to use it would be big help

**Comment by Tanay-ErrorCode** [comment]
@nishant0708
1. Create a custom hook.
``` typescript
function useNavigationPrompt(message = 'Changes you made, would not be saved', when = true) {
  const navigate = useNavigate();
  const location = useLocation();
  const [isBlocking, setIsBlocking] = useState(when);

  useEffect(() => {
    const handleBeforeUnload = (e: any) => {
      if (!isBlocking) return;
      e.preventDefault();
      e.returnValue = message;
    };

    window.addEventListener('beforeunload', handleBeforeUnload);

    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    };
  }, [isBlocking, message]);

  const handleNavigation = (path: string) => {
    if (isBlocking && !window.confirm(message)) {
      return;
    }
    navigate(path);
  };

  return { handleNavigation };
}
```
2. Call it in navbar
``` typescript
  const { handleNavigation } = useNavigationPrompt("Are you sure you want to leave this page?", true);
  const goToHomePage = () => handleNavigation('/');
/*Add more route links like articles, profile, etc.*/

/*Add onclick in NavLinks like this 
        onClick={goToHomePage}
*/
```
3. Modify the create event, article page such that when the user writes anything in wither the **title or the description**, a flag in `localStorage` sets to true separate for article and event creation.
4. Modify the hook to only trigger popup when the current `window.location` is either the event creation one or the article one. Trigger the alert message only when the flag in `localStorage `is **true**, reset it once published or site leaved.
