### ISSUE TITLE
feat: Add Preview Functionality to Event Creation Page

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#353]
**Is your feature request related to a problem? Please describe.**
There is no way to preview an event before publishing it. This makes it hard to check if all details are correct.

**Describe the solution you'd like**
Add functionality to preview button in create event page. This should show how the event will look once it's published, so users can review and make changes if needed.

**Describe alternatives you've considered**
None

**Additional context**
On clicking the preview button, The same card displayed on the event page muse appear with the details entered by the user.

**Comment by nishant0708** [comment]
hey can i work on this issue?

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead. Also fix #350 first.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 so on clicking preview a modal should open right with event card?

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012 please respond to above query whether possible

**Comment by Tanay-ErrorCode** [comment]
> hey @Tanay-ErrorCode @Doraemon012 so on clicking preview a modal should open right with event card?

@nishant0708 Yes, use MUI model.
