### ISSUE TITLE
feat: Publish event on filling the event details and make is present in Dashboard

### ISSUE THREAD

**Issue by Vijayaa21** [Tanay-ErrorCode/lupo-skill#355]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I would like to set up an event and have it prominently displayed on the dashboard for easy access. In case it's necessary to input event details, I want it to be clearly indicated to ensure that all necessary information is provided.

**Describe the solution you'd like**
I will make sure to add an asterisk mark to the required fill-in details to draw attention to them. Additionally, I will ensure that the event gets published and is visible in the dashboard once published.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Vijayaa21 Go ahead.

**Comment by Tanay-ErrorCode** [comment]
@Vijayaa21 Any updates?

**Comment by Vijayaa21** [comment]
> @Vijayaa21 Any updates?

yes, I am working on it.
