### ISSUE TITLE
feat: Develop live event WebRTC interface.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#358]
**Is your feature request related to a problem? Please describe.**

We currently manage meetings using Google Meet, but we want to enable WebRTC-based meetings to reduce reliance on third-party services.

**Describe the solution you'd like**
Implement a WebRTC-based calling system within our platform that allows for seamless audio and video communication. This system should include features such as screen sharing, recording, and chat functionality. It should be secure, scalable, and provide a user-friendly interface.

**Describe alternatives you've considered**
None

**Additional context**

![WebRTC Call Interface](https://github.com/user-attachments/assets/edef7690-d05e-462d-b5ab-4bebc8dc227e)

Develop an interface for meetings like the image above. Use MUI components.
For now use the route link "/#/meeting/:id"

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode i don't know will be able to do it or not but I wanna try

**Comment by Tanay-ErrorCode** [comment]
It's just UI for now. Go ahead @nishant0708

**Comment by nishant0708** [comment]
Oo okay 👍👍

**Comment by nishant0708** [comment]
![image](https://github.com/user-attachments/assets/5f3183e3-b6db-428e-b068-85f5d34fa23b)
hey @Tanay-ErrorCode see this need any changes let me know

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 This is good, but remove that lock icon and raise the PR.
