### ISSUE TITLE
feat: Scroll to top button 

### ISSUE THREAD

**Issue by divyansh-2005** [Tanay-ErrorCode/lupo-skill#365]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
We can have to scroll to top button to auto scroll to top

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@divyansh-2005 We do not need this, our content is not that long. Please take up any other issue or open one by yourself.
