### ISSUE TITLE
feat: Scroll to Top Button

### ISSUE THREAD

**Issue by AnkitLuhar** [Tanay-ErrorCode/lupo-skill#366]
**Is your feature request related to a problem? Please describe.**

Yes, the current website design does not include a "Scroll to Top" button, making it cumbersome for users to navigate back to the top of the page, especially on long pages.

**Describe the solution you'd like**

I would like to add a "Scroll to Top" button that appears when the user scrolls down a certain distance on the page. The button should smoothly scroll the user back to the top when clicked.

**Describe alternatives you've considered**

1.Adding a fixed button at the bottom-right corner of the screen, which appears only after scrolling down a specific distance.

2.Implementing a floating button that appears after a delay, providing a smooth scrolling experience.

**Additional context**
here are the ScreenShot:

![Screenshot (914)](https://github.com/user-attachments/assets/e4263819-be4a-479b-99be-7e7c41d2de97)

**Comment by AnkitLuhar** [comment]
@Tanay-ErrorCode Assign this issue under the Gssoc'24 and excited to contribute.

**Comment by Tanay-ErrorCode** [comment]
@AnkitLuhar We do not need this, our content is not that long. Please take up any other issue or open one by yourself.
