### ISSUE TITLE
Add More Information to Footerfeat: add title here

### ISSUE THREAD

**Issue by lovelymahor** [Tanay-ErrorCode/lupo-skill#367]
**Is your feature request related to a problem? Please describe.**
We need to update the footer of our website to include additional sections for improved user experience and compliance. Specifically, we want to add:

**Describe the solution you'd like**
Update the footer to include sections for newsletter signup, privacy policy, terms & conditions, and copyright information. Each section should have a clear link or form field as needed.
Newsletter Signup: A field for users to subscribe to our newsletter.
Privacy Policy: A link to our privacy policy page to inform users about data protection.
Terms & Conditions: A link to the terms and conditions page outlining user agreements.
Copyright Information: Updated copyright details to reflect the current year and ownership.

**Describe alternatives you've considered**
Alternative solutions include adding these sections to a separate "Legal" or "Information" page or using modal popups for additional information. However, integrating them directly into the footer ensures visibility and accessibility.

**Additional context**
These updates will improve user experience by centralizing key information and ensuring compliance with legal requirements.

**Screenshot**

![Screenshot (290)](https://github.com/user-attachments/assets/c58b6f54-08f8-45a8-96dd-d4d5ba9d92a6)

**Comment by lovelymahor** [comment]
hii @Tanay-ErrorCode ,
I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by Tanay-ErrorCode** [comment]
@lovelymahor We do not need this. Please take up any other issue or open one by yourself.
