### ISSUE TITLE
bug : Center loading indicator

### ISSUE THREAD

**Issue by himanshugoyal77** [Tanay-ErrorCode/lupo-skill#37]
**Describe the bug**
The loading indicator is below the nab bar. It should be centered for better user experience

**To Reproduce**
i will change the styles of the loading indicator

**Expected behavior**
it should be at center of the screen

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/92782099/0f4dd6bf-2772-449c-aec2-7288f7fb0ef4)

**Comment by Tanay-ErrorCode** [comment]
@himanshugoyal77 You can now work on this issue.
