### ISSUE TITLE
feat: Modify the navbar for Better visibility on scroll

### ISSUE THREAD

**Issue by sau-mili** [Tanay-ErrorCode/lupo-skill#374]
**Is your feature request related to a problem? Please describe.**
yes , readability issue with the navbar
![image](https://github.com/user-attachments/assets/8fb9fd8b-9719-4fc2-b113-e9c2c64e5c7e)

**Describe the solution you'd like**
when scrolled, the UI of navbar should accept a background color to improve visibility

**Describe alternatives you've considered**

**Additional context**

**Comment by sau-mili** [comment]
@Tanay-ErrorCode please check this

**Comment by Tanay-ErrorCode** [comment]
@sau-mili Please describe your approach.

**Comment by sau-mili** [comment]
I would add a fucntion such that when page is scrolled, it will add a class to the navbar to add  a background color with transition for smooth behaviour. In this way when scrolled it will have a background and hence the text will be visible.

**Comment by Tanay-ErrorCode** [comment]
@sau-mili Go ahead.
