### ISSUE TITLE
feat:If User has Created  0 events then In created Events Text Should Come With Button

### ISSUE THREAD

**Issue by nishant0708** [Tanay-ErrorCode/lupo-skill#378]
Okay See if User Has not created any Event then in That Case A Text should come Something Like "You Have Not Created any Event yet Create Now" and Button which will redirect to create event 

![image](https://github.com/user-attachments/assets/13326532-d9c9-43da-a137-d8705df59752)

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
