### ISSUE TITLE
feat: add  git commands for contribution from clone to making pull request

### ISSUE THREAD

**Issue by NAVJOT-786** [Tanay-ErrorCode/lupo-skill#380]
**Is your feature request related to a problem? Please describe.**
Yes, the current documentation for contributing to the project does not include detailed steps for setting up a local development environment, making changes, and submitting a pull request. This can be confusing for new contributors who are not familiar with the process.

**Describe the solution you'd like**
I would like to add a comprehensive section in the README.md that provides step-by-step instructions on how to clone the repository, create a new branch, make changes, commit those changes, push the branch, and submit a pull request. Additionally, I would like to include an example issue template to guide users in submitting feature requests and bug reports.

**Describe alternatives you've considered**
An alternative solution could be to create a separate CONTRIBUTING.md file that contains all the detailed steps for contributing. This file could be linked from the main README.md to keep the main file concise while still providing all necessary information.

**Additional context**

I M CONTRIBUTING UPRON GSSOC24

**Comment by NAVJOT-786** [comment]
please assign me the issue

**Comment by Tanay-ErrorCode** [comment]
@NAVJOT-786 The issue templates are already there, and you can find `CONTRIBUTING.md` **[here](https://github.com/Tanay-ErrorCode/lupo-skill/blob/main/CONTRIBUTING.md)**.

**Comment by NAVJOT-786** [comment]
but there are only 2 git commands it should contain all the commands from cloining to making the pull request i want to add all the commands
