### ISSUE TITLE
feat: Profile name or image click behavior in comments.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#383]
**Is your feature request related to a problem? Please describe.**
In an article, if we scroll down to the comments and try to click on the user's profile picture or name, nothing happens. We need it to open the person's profile.

**Describe the solution you'd like**
On clicking on either the profile or user name, his/her profile must open.

**Describe alternatives you've considered**
None

**Additional context**

![image](https://github.com/user-attachments/assets/846b109c-beb5-4104-aa33-1265b45ba126)

On clicking in the orange part, the user's profile must open.

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode can I work on this

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode can i also work on issue #298 ?
