### ISSUE TITLE
feat: Comment button click behavior

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#392]
**Is your feature request related to a problem? Please describe.**
Currently on clicking on comments icon, nothing happen, but, the content must automatically scroll down to comments and the focus must be on the text-box
 
**Describe the solution you'd like**
On click on comment icon in the articles page, the content must automatically scroll down to comments and the focus must be on the text-box.

**Describe alternatives you've considered**
None

**Additional context**

![image](https://github.com/user-attachments/assets/747f7d5f-d28d-49ff-b9e8-5df93464da51)

**Comment by Ayushmaanagarwal1211** [comment]
@Doraemon012 @Tanay-ErrorCode can i work on that

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 can i work on this?

**Comment by Ayushmaanagarwal1211** [comment]
@Doraemon012 @Tanay-ErrorCode can i work on that

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
