### ISSUE TITLE
feat: Add Legal Information and Newsletter Section to Footer

### ISSUE THREAD

**Issue by lovelymahor** [Tanay-ErrorCode/lupo-skill#393]
**Is your feature request related to a problem? Please describe.**
We need to enhance our website by adding legal information and a newsletter subscription section in the footer to ensure compliance and engage visitors.

**Describe the solution you'd like**
I would like to add a section in the footer of our website for legal information (Privacy Policy, Terms of Service, Cookie Policy) and a newsletter subscription form. This will make it easier for users to access important legal information and subscribe to our updates.

**Describe alternatives you've considered**
Placing legal information in a separate page and linking to it from the main menu, but it might be less accessible.
Including the newsletter form in a sidebar instead of the footer, but this could affect the design and user experience.

**Additional context**
This feature will ensure compliance with regulations and enhance user engagement by providing an easy way for visitors to stay informed. Below is a visual example of the proposed footer section design.

**Screenshot**
![Screenshot (340)](https://github.com/user-attachments/assets/5cc3991e-00ab-421d-9cd7-c6b7d37140e0)

**Comment by lovelymahor** [comment]
Hello @Tanay-ErrorCode ,
Please review the changes at your earliest convenience and consider merging them. Thank you!

**Comment by Tanay-ErrorCode** [comment]
@lovelymahor When an issue referencing the same problem is closed, please don't open the same issue again. PTAL #367 .
