### ISSUE TITLE
feat: Adding Scroll indicator to the site

### ISSUE THREAD

**Issue by Sourabh782** [Tanay-ErrorCode/lupo-skill#394]
**Is your feature request related to a problem? Please describe.**
I wanted to add a dynamic scroll indicator to top of the site, Improving the interactivity of the user

**Describe the solution you'd like**
i wanted to include a dynamic scroll indicator to the site

**Describe alternatives you've considered**

**Additional context**
![Screenshot 2024-08-05 204846](https://github.com/user-attachments/assets/ff3db622-8c6c-42ac-a53e-acb328152a4a)

I want to work on implementing the following feature

**Comment by Tanay-ErrorCode** [comment]
@Sourabh782 Go ahead. add that **only** in the article reading page.

**Comment by Sourabh782** [comment]
Sure @Tanay-ErrorCode

**Comment by Sourabh782** [comment]
@Tanay-ErrorCode  can u help me setup firebase, i have setup it but having an error? 
![Screenshot 2024-08-08 155827](https://github.com/user-attachments/assets/aafdddfc-b0b8-4b69-9a50-c2dc07dc69b9)
Any way to resolve it?

**Comment by Tanay-ErrorCode** [comment]
@Sourabh782 Go through [this video](https://youtu.be/iE9CTZnW9NU?si=o5r6DQJajSpF9Lcn). Please let us know if the error persists

**Comment by Sourabh782** [comment]
Thanks
