### ISSUE TITLE
feat: File add support for events.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#397]
**Is your feature request related to a problem? Please describe.**
Currently, there is no functionality to add files to events. Organizers may need to attach additional files such as PDFs or PPTs to provide detailed information or resources related to the event.

**Describe the solution you'd like**
Add the capability for event organizers to upload and attach files (e.g., PDFs, PPTs) to their events. This feature should allow organizers to:
- Attach relevant files during the event creation process.
- Enable attendees to download and access these files.

**Describe alternatives you've considered**
None

**Additional context**
Set maximum size for files. 

![image](https://github.com/user-attachments/assets/762b46e5-9aa2-41fb-b473-3ecd1d1dcb96)

Add the **folder** named event attachments.

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode can I work on this issue

**Comment by nishant0708** [comment]
Just let me know the design wise  where organizer can add option of pdf like in design 

And for downloading as well

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 In the create event page, just like the add banner, let user pick any file and exclaim (toast) if file not supported.


![image](https://github.com/user-attachments/assets/a8b46247-d591-4ffd-a454-bb301fac5a38)

Once the event is registered, in the event details page, another card must come with heading **"attached files"**. Inside that card, the icon of the file will come with the name underneath.

**Comment by nishant0708** [comment]
Cool okay
