### ISSUE TITLE
Dashboard fix 

### ISSUE THREAD

**Issue by Ankesh2004** [Tanay-ErrorCode/lupo-skill#4]
In dashboard all the created and joined events should be shown under different categories, but they are being shown under "Created Events" only.
Kindly assign me this issue under GSSOC'24.

**Comment by Doraemon012** [comment]
@Ankesh2004 Any updates ?

**Comment by Riyasharma1311** [comment]
@Ankesh2004 this looks an interesting one to work on . Kindly assign me this issue

**Comment by Doraemon012** [comment]
@Riyasharma1311 The dashboard should show the events **created by user** and the events **registered by user**.

**Comment by Tanay-ErrorCode** [comment]
@Riyasharma1311 Any updates?

**Comment by Riyasharma1311** [comment]
Yes ! I'm working on it , will send a pull request by EOD

**Comment by Annu117** [comment]
Can i work on this?
