### ISSUE TITLE
bug : Can create events before current time.

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#403]
**Describe the bug**
Currently, we can create events before the current time and date. We need to fix this behaviour.

**To Reproduce**

1. Go to Create event page
2. Fill all the required details
3. Try to set the date and time before today
4. See issue

**Expected behavior**
The application should give popup, saying **“Events cannot be scheduled for past dates. Please select a future date.”**

**Screenshots**
None

**Additional context**
None

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode can I work on this

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
