### ISSUE TITLE
bug : Can't access any page without login

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#404]
**Describe the bug**
Without login, users should be able to access some pages.

**To Reproduce**

1. Go to Website
2. Logout
3. Click any on the links in navbar
4. See the issue

**Expected behavior**
The users must be able to access 
1. Events page
2. Articles page, When click on **Create**, the login popup must come.
3. Create event page, When click on **publish**, the login popup must come.

**Screenshots**
None

**Additional context**
Not logged in user must not be able to access
1. Profile Page
2. Dashboard
3. Should not be able to comment or like article.

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode can I work on this

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 Go ahead.
