### ISSUE TITLE
bug :  Move "Create Event" Button from Navbar to Events Page

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#407]
**Describe the bug**
The `Create Event` button is currently placed in the navbar, unlike the `Create Article` button on the Articles page.

**To Reproduce**

1. Navigate to the `https://lupo-skill.web.app`.
2. Observe the "Create Event" button in the navbar.
3. Compare with the Articles page, where the "Create" button is placed inside the page.

**Expected behavior**
The "Create Event" button should be moved from the navbar to the Events page to maintain design consistency, similar to how the Articles page has its "Create" button.

**Screenshots**

![image](https://github.com/user-attachments/assets/acbc561a-f629-4eab-8c15-6d74704eca7d)

![image](https://github.com/user-attachments/assets/54ccc3d4-b35f-4426-897d-61d86d4bddeb)

**Additional context**
NA

**Comment by nishant0708** [comment]
hey @Tanay-ErrorCode @Doraemon012 can i work on it?
