### ISSUE TITLE
bug : Make Navbar Logo and Name Clickable to Redirect to Homepage

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#409]
**Describe the bug**
The website's logo and name in the navbar are currently not clickable and do not redirect to the homepage, which is a common functionality.

**To Reproduce**

1. Navigate to the `https://lupo-skill.web.app/`.
2. Observe that the logo and website name in the navbar are not clickable.
3. Compare this with GitHub, where clicking on the logo redirects to the homepage.

**Expected behavior**
The logo and website name in the navbar should be clickable and should redirect users to the website's homepage, similar to the functionality on GitHub.

**Screenshots**
NA.

**Additional context**
NA.

**Comment by nishant0708** [comment]
hey @Doraemon012  assign it to me
