### ISSUE TITLE
bug : Navbar overlapping with page contents

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#41]
**Describe the bug**
The Navbar is overlapping with the website contents. 

**To Reproduce**
1. Run the lupo-skill website locally
2. Go to 'Dashboard'
3. See that the navbar is overlapping with the page contents

**Expected behavior**
The navbar should not overlap with the contents.

**Screenshots**

[Navbar issue](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/0faa07e5-44fc-484d-9501-98a2bfc047be)

**Additional context**
No additional context at this point.

**Comment by himadeepthi1** [comment]
Hello ! @Doraemon012  , I would like to work on this issue

**Comment by Doraemon012** [comment]
@himadeepthi1 You can now work on this.

**Comment by Tanay-ErrorCode** [comment]
@himadeepthi1 Any updates?

**Comment by himadeepthi1** [comment]
@Doraemon012 kindly review #68

**Comment by himadeepthi1** [comment]
> @himadeepthi1 Any updates?

I have made a pr #68 kindly review it

**Comment by himadeepthi1** [comment]
Fixed the overlapping of navbar @Doraemon012 kindly review #82
