### ISSUE TITLE
bug : Error When Closing Firebase Signup Popup Without Completing Signup

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#42]
## Describe the bug
When clicking on the signup button and then closing the popup without completing the signup process, an error is thrown: ?
> Uncaught (in promise) FirebaseError: Firebase: Error (auth/popup-closed-by-user).

## To Reproduce

1. Navigate to the website.
2. Click on the login button.
2. Click on the signup button in popup.
4. Observe the error in the console.

## Expected behavior
The system should handle the closure of the signup popup without throwing an error related to auth/popup-closed-by-user.

## Screenshots
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/41f046c3-de99-48a1-866f-5005a0a7ba36)

## Additional context
None

**Comment by nishant0708** [comment]
i could fix this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 You can work on this issue.
