### ISSUE TITLE
bug : Allowing All File Types for Upload in Create Event Popup

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#43]
## **Describe the bug**
When creating an event using the **'Create Event' popup**, it is possible to upload files of any type for the **event banner**, which should be restricted to specific file types.
The same bug is in **edit profile popup** that asks for **profile image and banner**.

## **To Reproduce**
1. Go to the 'Create Event' popup.
2. Click on the **file upload** button.
3. Select a file with an unsupported type (e.g., `.py`, `.js`, etc.).
4. Observe that the file is uploaded without any validation error.

## **Expected behavior**
The file upload should be restricted to specific file types (e.g., `.jpg`, `.png`, other image types). Unsupported file types should not be allowed and should trigger a validation error toast.

## **Screenshots**
None

**Comment by nishant0708** [comment]
i could fix this

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 You can work on this issue.
