### ISSUE TITLE
bug : Spinner Persists on Profiles with No Events

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#45]
## **Describe the bug**
When opening a profile, if the user has not created or joined any events, the spinner continues to spin indefinitely.

## **To Reproduce**
1. Open the profile of a user who has not created or joined any events.
2. Observe that the spinner keeps spinning without stopping.

## **Expected behavior**
The spinner should stop, and a message should be displayed stating “No joined events found.” for joined events and for created events “No created events found”

## **Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/efec52ef-47d8-4123-9e8d-24f4f19dcd69)

## **Additional context**
None

**Comment by Doraemon012** [comment]
@Tanay-ErrorCode Please assign this to me.

**Comment by nishant0708** [comment]
hey I can fix this issue

**Comment by Doraemon012** [comment]
@nishant0708 You can now work on this.
