### ISSUE TITLE
feat: Implement Profile Editing Feature

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#50]
## **Is your feature request related to a problem? Please describe.**
Currently the website gives Profile Editing popup on clicking on **Edit Profile** button but it lacks the backend to update the user data.

## **Describe the solution you'd like**
Make this **Edit Profile** feature work by updating the data in firebase RTDB and for banner and profile image use firebase storage.

## **Additional context**
The structure in which the data must be stored is:
* User Details (`users/{uid of user}`):*
![image (2)](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/2787e172-175a-4a9c-8866-7463989ab104)

* Banner and profile image:
 Currently there are `user-banners` and `event`-banners, add a new folder **user-profile-pics** 
![BNP](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/b28edf3d-2c55-47f7-8535-00a09058e032)
* Inside the `user-profile-pics` the data must be stored in this format (similar to banner storage given in the image) :
![image (4)](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/565c79fc-1f2f-43e7-97a7-5746511c983f)

FORMAT :  **user-profile-pic-`{user UID}`**

* The *UID is saved in the local storage* and can be also retrived by *`auth.currentUser.uid`*

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me

**Comment by Doraemon012** [comment]
@nishant0708 How are you planning to implement this? Please clarify your approach.

**Comment by nishant0708** [comment]
And even if my method is incorrect, I will make sure it functions correctly in accordance with the previous comment, so assign me this problem.

**Comment by nishant0708** [comment]
Hey @Tanay-ErrorCode @Doraemon012  please assign it to me

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 You can work on this now.
