### ISSUE TITLE
bug : Missing 404 Error Page

### ISSUE THREAD

**Issue by PratikMane0112** [Tanay-ErrorCode/lupo-skill#53]
When there is any error in website while navigating through pages, there is not a 404 error page.

![Screenshot 2024-05-16 182305](https://github.com/Tanay-ErrorCode/lupo-skill/assets/153143167/1479e022-a9d7-4204-8979-5a036b7a0940)

I will create a good 404 error page which will match with website environment.
Below is just an rough idea that I have :

![404](https://github.com/Tanay-ErrorCode/lupo-skill/assets/153143167/95ece66c-614e-4c92-9259-97f00efe5e99)

I will edit it to add button to navigate to home page & also make it responsive to have a unique error page for website.

**Expected behavior**
A clear understanding to users using website when such error occurs and the navigate back to home page.

Plz assign me this issue & also add labels.

**Comment by Tanay-ErrorCode** [comment]
@PratikMane0112 You can work on this issue. You will be unassigned if inactive for 2 days.

**Comment by PratikMane0112** [comment]
Ok, I will complete it today.
