### ISSUE TITLE
feat: Implement Testimonials Section on Homepage

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#59]
### **Is your feature request related to a problem? Please describe.**
Our homepage currently lacks a testimonials section, which could help establish trust and credibility with visitors. Without testimonials, potential users might hesitate when considering our service.

### **Describe the solution you'd like**
Implement a testimonials section on the homepage. Since we don't have real testimonials yet, include sample data in the testimonials. 

**To achieve this, you need to create:**
1. A testimonial card component.
2. A carousel for the testimonial cards.

### **Additional context**
- Please refer to the attached image for a visual representation of the desired testimonials section along with the testimonial card component.
- The theme already defined in `theme.tsx` to maintain consistency with our overall website theme.
- The exact UI design can be found in this [Figma Design](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=53%3A152&t=f3uoGr0gBBzMlrcS-1).
- For creating the carousel, you can use [React Bootstrap Carousel](https://react-bootstrap.netlify.app/docs/components/carousel/).

**Technologies to use:**
- MUI
- React Bootstrap
- CSS

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/247afce3-b032-4455-b0f4-fdf6ad17447a)

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/9d7571aa-e6af-4b62-8701-4fed76ff20a5)

**Comment by nishant0708** [comment]
hey can you assign me this issue under gssoc24 .I can create this card

**Comment by abhiperfect** [comment]
I also want to work on this issue, could you please assign me this this issue.

**Comment by himadeepthi1** [comment]
Hello ! @Doraemon012 , I would like to work on this issue , could you assign this issue to me

**Comment by Doraemon012** [comment]
@himadeepthi1 and @abhiperfect We assign issues on a first-come, first-served basis. If you would like, you can take up any other open issues or open one yourself if needed.
