### ISSUE TITLE
feat: Add an About Page

### ISSUE THREAD

**Issue by Manav173** [Tanay-ErrorCode/lupo-skill#61]
Is your feature request related to a problem? Please describe.

Users often express frustration when they cannot easily find information about our company, our mission, and the team behind our products. This lack of transparency can lead to mistrust or a sense of detachment from our brand. An About Page is crucial for providing this information in a clear and accessible manner.

Describe the solution you'd like

I propose the addition of an About Page to our website. This page will provide comprehensive information about our company, including our history, mission, values, and team members. It will also highlight our commitment to quality, customer satisfaction, and any unique aspects that set us apart from our competitors. The page should be easily accessible from the main navigation menu.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @Tanay-ErrorCode  .

**Comment by Tanay-ErrorCode** [comment]
@Manav173 The contact us section must be in the footer. We have already planed for the footer.

**Comment by Manav173** [comment]
I have created an issue to create an about page not a contact us page in the footer @Tanay-ErrorCode .

**Comment by Tanay-ErrorCode** [comment]
@Manav173 The both sections must be in footer.
