### ISSUE TITLE
feat: add contact us page

### ISSUE THREAD

**Issue by roysammy123** [Tanay-ErrorCode/lupo-skill#62]
**Is your feature request related to a problem? Please describe.**
Users often struggle to find ways to get in touch with our team. Without a dedicated contact page, it becomes challenging for users to reach out for support, provide feedback, or make inquiries, leading to a poor user experience and potential loss of engagement.

**Describe the solution you'd like**
I would like to have a dedicated Contact Page on the website that provides users with various methods to contact.

**Comment by Tanay-ErrorCode** [comment]
@roysammy123 The contact us section must be in the footer. We have already planed for the footer.
