### ISSUE TITLE
feat: Implement footer on website

### ISSUE THREAD

**Issue by jain-anshika** [Tanay-ErrorCode/lupo-skill#63]
**Is your feature request related to a problem? Please describe.**
- A footer is a important part of every website.
- By listing your pages in the footer, you can incorporate relevant keywords on every page of your website.
- Footers are also home to key information like company contact details, which should be easily accessible to your users at all times.

**Describe the solution you'd like**
- Add Footer on website to make it look professional.
- Add logo in the footer.
- Add social media links
- Add about us sections in the footer

Please assign this issue to me under GSSoC'24.
I will not disappoint you and would like to work on this issue.
Thank you!!

**Comment by Tanay-ErrorCode** [comment]
@jain-anshika I am assigning this issue to you, we suggest using the below design for the footer.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/871bbbbc-9058-49df-8323-9172ec2b6602)


The exact UI design can be found in [this figma design](https://www.figma.com/design/vDVEoB5YY32EUoeFWtXaCA/Lupo-Skill?node-id=53%3A152&t=CupRy1RxQZZpeWzz-1)

**Comment by Doraemon012** [comment]
@jain-anshika Any updates ?

**Comment by Annu117** [comment]
@Doraemon012 I would like to work on this under gssoc'24.

**Comment by Tanay-ErrorCode** [comment]
@Annu117 Assigned, try to complete it ASAP.
