### ISSUE TITLE
feat: Improving Tag Input System

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#65]
## **Is your feature request related to a problem? Please describe.**
Right now, we have to separate tags with commas when entering them. This is annoying and less user friendly.

## **Describe the solution you'd like**
I'd like a tag input feature similar to YouTube, where pressing Enter automatically creates a new tag. This would make tagging much easier and more user friendly.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/c26173b0-12d8-4bbc-87b1-9902656ead15)
Use this design :
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/7a58836a-fc4d-436b-aafa-91def8a357c2)

## **Additional context**
- **Please note, the theme colors should not change with this update.**
- And in the database, **currently the tags are stored as comma separated, this format should not change** .
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/aa9fb290-c887-4b14-815e-bd7f237d6176)

**Comment by Tomkndn** [comment]
Hey, I want to work on this issue,Kindly assign me this task.
So that I can start working on this

**Comment by Tanay-ErrorCode** [comment]
@Tomkndn You can work on this issue now.

**Comment by Tomkndn** [comment]
My suggestion for the UI for the input box is attached below as because after some inputs the box will be occupied by the tags.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/105445488/8d0a711c-b7d4-47b2-9644-0833d487f605)
After your approval, I will raise my PR.

**Comment by Doraemon012** [comment]
@Tomkndn  LGTM
Please use the [MUI chip component (deletable)](https://mui.com/material-ui/react-chip/#deletable) for the tags.

**Comment by Tomkndn** [comment]
Please add the same label which is present in the merged PR.
