### ISSUE TITLE
feat: Need to fix the Title in the Events page as it's not clearly visible and gets half covered by the navbar

### ISSUE THREAD

**Issue by satyam8932** [Tanay-ErrorCode/lupo-skill#66]
**Is your feature request related to a problem? Please describe.**
Need to fix the Title in the Events page as it's not clearly visible and gets half covered by the navbar

**Describe the solution you'd like**
Will you some styling like margin and paddings to fix the issues

**Describe alternatives you've considered**
Otherwise I will use frameworks

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/82116707/45eeb21a-cd75-4104-9058-b185a00a23d1)

Please assign me this issue as Gssoc with Level

**Comment by satyam8932** [comment]
I have also contributed in other Gssoc projects and it got approved as well You can check this PR for reference 

https://github.com/abhay-raj19/FitBody/issues/126

**Comment by Doraemon012** [comment]
@satyam8932 An issue is already open for this.
