### ISSUE TITLE
Updated UI 

### ISSUE THREAD

**Issue by jain-anshika** [Tanay-ErrorCode/lupo-skill#7]
I want to enhance the UI using react bootstraps please assign this issue to me under gssoc.

**Comment by Tanay-ErrorCode** [comment]
@jain-anshika There is no need to improve UI right now. I will open UI specific issues when necessary.
I am closing this as not planned

**Comment by jain-anshika** [comment]
Okay please assign me if you open any UI related issue. 
Thank you!
