### ISSUE TITLE
bug : Star on Github button not working

### ISSUE THREAD

**Issue by ansh-h-mehta** [Tanay-ErrorCode/lupo-skill#70]
**Describe the bug**
Give us a Star button located on left-bottom corner of the website is not working.

**To Reproduce**

1. Go to https://lupo-skill.web.app/
2. Scroll down to ' Give us a star! ⭐ '
3. Click on 'Star on GitHub' button

**Expected behavior**
When the user clicks on the button, the user expects to be redirected to this GitHub Repository in order to star it.

**Screenshots**
I have included the Screenshot of the issue.

![image_2024-05-18_184430536](https://github.com/Tanay-ErrorCode/lupo-skill/assets/99081110/8aca99cf-9cc3-4cb3-9f15-222adb6541b7)

**Additional context**

**Comment by ansh-h-mehta** [comment]
Kindly assign me this issue under GSSOC'24.

**Comment by Tanay-ErrorCode** [comment]
@ansh-h-mehta Any updates ?

**Comment by ansh-h-mehta** [comment]
Hi I am working on it, currently I am having exams so I am occupied there, but I'll fix it in a few hours.

**Comment by AnirbanChattopadhyay-2004** [comment]
I can solve this under 30 minutes and assign this to me.

**Comment by DarkAngelu** [comment]
Could you please assign this issue to me?
