### ISSUE TITLE
light/dark mode

### ISSUE THREAD

**Issue by krithika2543** [Tanay-ErrorCode/lupo-skill#73]
**Is your feature request related to a problem? Please describe.**
Currently the users can only use the web-app in light mode. To enhance user experience, we can add a night mode option.

**Describe the solution you'd like**
I want to add a light/dark mode toggle feature. This feature would allow users to switch between light and dark themes based on their preference or the ambient lighting conditions.

**Additional context**
This is under GSSOC'2024 Contribuition

**Comment by Yogesh-ok55** [comment]
i want to work on this project. kindly assign this issue to me

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55 and @krithika2543 An issue is already open for this. #9

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55, @krithika2543  We are planning to change the entire UI. It will be better to implement theme switching after the UI is ready.

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by nisargaa20** [comment]
If no one is working on this issue. Could you kindly assign me this issue?

**Comment by tkshsbcue** [comment]
@Tanay-ErrorCode i would like to work on this issue
