### ISSUE TITLE
bug : Heading of Events page is cutting down by header .

### ISSUE THREAD

**Issue by YukiP7** [Tanay-ErrorCode/lupo-skill#74]
**Describe the bug**
Heading at "Events Page " is cutting from upward by the header , the required white space needed also I can make the heading more appropriate and eye catching .

**To Reproduce**

1. Go to Home.
2. Click on Events at Header .
3. Scroll down to heading 

**Screenshots**
![Screenshot 2024-05-19 115439](https://github.com/Tanay-ErrorCode/lupo-skill/assets/109288720/48bf126e-24da-4d3b-9f39-6fff7002238a)
](url)

**Additional context**
Please assign me this issue and label it as Gssoc with level 1 .

**Comment by Tanay-ErrorCode** [comment]
@YukiP7 An issue is already open for this. #41
