### ISSUE TITLE
Add Social Media Links (Twitter, Instagram, YouTube)

### ISSUE THREAD

**Issue by krithika2543** [Tanay-ErrorCode/lupo-skill#75]
**Is your feature request related to a problem? Please describe.**
Currently, user profiles do not include quick-access links to their social media accounts, such as Twitter, Instagram, and YouTube. This limits users' ability to connect their profiles, making it harder for others to find and follow them on these platforms.

**Describe the solution you'd like**
I propose the addition of clickable social media icons (e.g., Twitter, Instagram, YouTube) under each user profile

**Additional context**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/133742234/498f1d5e-1803-4282-a508-c00b9d038698)
This is under Gssoc'2024 contribution

**Comment by Tanay-ErrorCode** [comment]
@krithika2543 Are you planning to work on only frontend or backend as well?

**Comment by krithika2543** [comment]
@Tanay-ErrorCode, I am interested in working on both frontend and backend.

**Comment by Tanay-ErrorCode** [comment]
@krithika2543 You can work on this.
