### ISSUE TITLE
bug : [Text overlapping with navbar in Event page]

### ISSUE THREAD

**Issue by Yogesh-ok55** [Tanay-ErrorCode/lupo-skill#76]
**Describe the bug**
on Event page heading "All Events" is not properly alligned.

**To Reproduce**

1. Go to 'Home'
2. Click on 'Event'
3. On the Top below navbar

**Expected behavior**
It should move slightly below so it can be seen properly

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/127961738/86145182-f338-4168-be2e-efde7e8db535)

**Additional context**
Kindly assign this issue to me so that i can start working on this project.

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55  An issue is already open for this. #41
