### ISSUE TITLE
bug : Allowing All File Types for Upload in Edit Profile Popup

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#79]
## **Describe the bug**
When editing profile using the **Edit Profile popup**, it is possible to upload files of any type for the **banner as well as for profile image**, which should be restricted to image file type.

## **To Reproduce**
1. Go to the 'Edit Profile' popup.
2. Click on the **file upload** button.
3. Select a file with an unsupported type (e.g., `.py`, `.js`, etc.).
4. Observe that the file is uploaded without any validation error.

## **Expected behavior**
The file upload should be restricted to specific file types (e.g., `.jpg`, `.png`, other image types). Unsupported file types should not be allowed and should trigger a validation error toast.

## **Screenshots**
None

**Comment by nishant0708** [comment]
hey assign me this issue
