### ISSUE TITLE
feat: Add Image Cropping Feature for Profile Pictures

### ISSUE THREAD

**Issue by Doraemon012** [Tanay-ErrorCode/lupo-skill#80]
## **Is your feature request related to a problem? Please describe.**
Users currently do not have the ability to crop their profile pictures, which can result in uneven and improperly framed profile images.

## **Describe the solution you'd like**
Add a feature that allows users to crop their profile pictures in a 1:1 ratio using a tool like Cropper.js. This will ensure that all profile pictures are uniform and properly framed.

## **Describe alternatives you've considered**
None

## **Additional context**
Adding a front-end cropping tool like Cropper.js will enhance the user experience by allowing them to manually adjust and preview their profile picture before saving it. Here is a link to Cropper.js for reference: [Cropper.js](https://fengyuanchen.github.io/cropperjs/).

**Comment by nishant0708** [comment]
hey can you assign me this issue

**Comment by Doraemon012** [comment]
@nishant0708 You can work on this now.
