### ISSUE TITLE
feat:  Add More Social Websites to Profile Section.

### ISSUE THREAD

**Issue by abhiperfect** [Tanay-ErrorCode/lupo-skill#84]
### Feature Request: Add More Social Websites to Profile Section

**Is your feature request related to a problem? Please describe.**
Users currently cannot add multiple social websites to their profile, limiting their ability to share comprehensive information about their online presence and work.

**Describe the solution you'd like**
Implement a feature that allows users to add multiple social website URLs to their profile section. This should include fields in the profile settings where users can input various social media or website URLs, and these links should be displayed on their public profile. Each link could include an optional description or title for better context.

**Describe alternatives you've considered**
- Allowing users to add a single website URL, which might not fully capture their online presence.
- Providing predefined fields for specific social networks (e.g., LinkedIn, Twitter, GitHub) rather than customizable fields for any website.

**Additional context**
This feature would significantly enhance user profiles by allowing them to showcase all their relevant social media and professional websites. It would help in networking, showcasing users' work, and providing a more comprehensive view of their online presence. Ensure to add validation to check the format of the URLs and possibly icons to visually differentiate between different social networks.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Tanay-ErrorCode** [comment]
@abhiperfect Closing as an issue is already open for this #75
