### ISSUE TITLE
feat: Their should be option to delete created event by user.

### ISSUE THREAD

**Issue by abhiperfect** [Tanay-ErrorCode/lupo-skill#86]
### Feature Request: Delete Created Event

**Is your feature request related to a problem? Please describe.**
Currently, users do not have the option to delete events they have created. This can lead to clutter and confusion if events are canceled or no longer relevant.

**Describe the solution you'd like**
Implement a feature that allows users to delete events they have created. This option should be easily accessible from the event management interface and should confirm the deletion action to prevent accidental deletions.

**Describe alternatives you've considered**
- Providing an option to archive events instead of deleting them, so they are no longer active but still retrievable.
- Allowing users to mark events as canceled, which would remove them from active listings but retain the information.

**Additional context**
This feature would help users manage their events more effectively, keeping their event list organized and relevant. Consider implementing confirmation prompts and ensuring that deleting an event does not affect other users or linked data inadvertently.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Doraemon012** [comment]
@abhiperfect Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the project. Please wait until your existing issues are closed

**Comment by Tomkndn** [comment]
Basically, I have to just delete a event when a user clicks on the event button right?
So, kindly assign me this issue.

**Comment by Dhevamuthu** [comment]
I would Like to work on this issue as a gssoc contributor.. please assign this task to me

**Comment by nishant0708** [comment]
Hey Can you assign me this issue

**Comment by Aditijainnn** [comment]
Please can you assign me this issue @Doraemon012
