### ISSUE TITLE
feat: Update the Landing page

### ISSUE THREAD

**Issue by AshishKumarSamantaray** [Tanay-ErrorCode/lupo-skill#89]
**Is your feature request related to a problem? Please describe.**
The page is too clumsy to describe what you are and who you are. We should remember that first impression lasts long. My design will help user stay longer in teh page and explore it.

**Describe alternatives you've considered**
Below is a figma design animated one which can help you know more about my idea.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/121350516/e0c4cb5d-4a18-46c4-9d6d-7772c8b6d80c

**Comment by Tanay-ErrorCode** [comment]
@AshishKumarSamantaray We do not need this for now.
