### ISSUE TITLE
Enhancing Website SEO with Meta Elements 

### ISSUE THREAD

**Issue by Astha86** [Tanay-ErrorCode/lupo-skill#92]
I've noticed an opportunity to improve the SEO performance of the website. Currently, it lacks essential meta elements such as keywords and author information.

Improving SEO through these meta tags is crucial as it directly impacts the website's visibility and search engine ranking. It is require to add these elements, to increase the chances of appearing higher in search results, leading to greater organic traffic and improved online presence.

@Tanay-ErrorCode Kindly assign me this issue under GSSOC'24.

**Comment by Doraemon012** [comment]
@Astha86 Please describe your approach.

**Comment by Astha86** [comment]
I will enhance SEO by adding relevant meta tags:

- keywords to highlight essential terms (whenever anyone search these keywords the website popup on page), 
- an author tag for credibility
- a compelling meta description to summarize content. 

This approach increases visibility, boosts search engine ranking, and drives organic traffic.

## Implementation Example :-

<meta name="keywords" content="Relevant keywords  ">
<meta name="author" content=" Name of the project Admin ">
<meta name="description" content="Proper description of the web page ">

@Doraemon012 , if you still have any query you can ask me.

**Comment by Doraemon012** [comment]
@Astha86 Ok, go ahead.
