### ISSUE TITLE
bug : Improving margin between title of the page and navbar and using a better background for each page.

### ISSUE THREAD

**Issue by Rakshit-gen** [Tanay-ErrorCode/lupo-skill#93]
**Describe the bug**
The title of the pages and the navbar have really small margin making it took unattractive+no background designs.

**To Reproduce**

1. Go to Events or dashboard.
2. See the title.
3. See error.

**Expected behavior**
There should be more margin between the title and the navbar and a better background gradient.

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/64471316/e5b29a8f-c3f6-41a8-8831-93e91d3beeb2)

**Additional context**
Please assign this issue to me, I am a GSSoC contributor.

**Comment by piyushvermaa** [comment]
can you please assign this issue to me, i can fix it!!!

**Comment by Doraemon012** [comment]
We do not need any background designs.
