### ISSUE TITLE
feat: Image Compression before upload

### ISSUE THREAD

**Issue by Tanay-ErrorCode** [Tanay-ErrorCode/lupo-skill#96]
## **Is your feature request related to a problem? Please describe.**
We need to make sure that all uploaded **banner** images are in **16:9 aspect ratio** and are **less than 200KB** in size for better storage and faster loading times. For the **profile pictures**, they should be **less than 100KB** and in **1:1 ratio**

## **Describe the solution you'd like**
When an image is uploaded, a popup should appear allowing users to resize the banner to a 16:9 ratio using `react-easy-crop`. The user should crop the image, and it should be compressed to under 200KB before being uploaded. And for the profile picture, the procedure will be the same but ratio must be 1:1 and it must be compressed under 100KB.

## **Describe alternatives you've considered**
We thought about resizing images on the server after they are uploaded, but this takes control away from the user and might not give the best result.

## **Additional context**
This feature will improve storage and performance. Currently, there is already cropper for the profile picture, keep it as it is, but add the compression funtionality.
Cropping tool : [react-easy-crop](https://www.npmjs.com/package/react-easy-crop)
Sample functionality:

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/64b05855-df16-4fda-b05b-3d9e249ca7b6)

**Comment by nishant0708** [comment]
assign me this issue

**Comment by Tanay-ErrorCode** [comment]
@nishant0708 You can work on this now.

**Comment by singhJasvinder101** [comment]
@Tanay-ErrorCode I would like to resolve the issue assign me
