### ISSUE TITLE
bug : Toggle Button Doesn't Close Automatically on Navbar Links Click (Mobile View)

### ISSUE THREAD

**Issue by kaali001** [Tanay-ErrorCode/lupo-skill#97]
**Describe the bug**
In the mobile view of the website, the toggle button on the navbar fails to close automatically upon clicking any of the navbar links. This issue results in an inconvenience for users navigating the site on mobile devices as the navbar remains open, obstructing the view of the content.

**To Reproduce**

1. Access the website on a mobile device or resize the browser window to simulate a mobile view.
2. Open the navbar menu by clicking on the toggle button.
3. Click on any of the navbar links to navigate to a different page.

**Expected behavior**
Upon clicking any navbar link, the navbar menu should automatically close, providing a seamless and intuitive browsing experience on mobile devices.

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/115466381/af6539d2-8ce5-45e5-9649-891cbadb8542)

**Additional context**

- Issue occurs consistently across various mobile devices and browsers.
- The problem seems to be isolated to the mobile view as the navbar functions correctly on desktop view.

Assign this issue to me under GSSoC label and some level, so that I can start working on this.

**Comment by kaali001** [comment]
@Tanay-ErrorCode  assign me this issue.

**Comment by nishant0708** [comment]
Hey I can fix this Issue

**Comment by kaali001** [comment]
@nishant0708 , I have fixed it , making the PR

**Comment by masterboy376** [comment]
Hello @Tanay-ErrorCode, I would like to work on the issue under GSSoC'24. I am now available.

**Comment by kaali001** [comment]
@Doraemon012  please add the label of difficulty level.
