### ISSUE TITLE
bug : [ For Upcoming Events It is showing Expired ]

### ISSUE THREAD

**Issue by Yogesh-ok55** [Tanay-ErrorCode/lupo-skill#99]
**Describe the bug**
On Event page, for Upcoming Events , the button text is expired, only for present day like if i create an Event on 23/05/2024 and timing is 9:00PM then it will show expired 

**To Reproduce**

1. Go to 'Home'
2. Click on 'Events'
3. Scroll down on 'Events page'

**Expected behavior**
For upcoming Events it should display Register.

**Screenshots**
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/127961738/6717f981-fcd4-4aaa-93b0-ba039d68ce9b)
.

**Additional context**
I would like to work on this project to solve this error kindly assign this issue to me.

**Comment by Doraemon012** [comment]
@Yogesh-ok55 Please describe your approach for solving the issue.

**Comment by Yogesh-ok55** [comment]
The person who have created this component is comparing only dates and not time like if it is 23/05/2024 it will show expired for current and previous dates and for further dates it will show register , so  in my approach I will also compare time and accordingly the button will display register or expired

**Comment by Tanay-ErrorCode** [comment]
@Yogesh-ok55 Any updates?

**Comment by Yogesh-ok55** [comment]
I am working on this it , will be done within 2 days
